<?php

$com=mysql_connect("localhost", "u705076634_longfash" ,"Dds76sd67gdcg");
mysql_set_charset('utf8',$com);
mysql_select_db("u705076634_longfash", $com) or die(mysql_error());

$nawigacja_kategoria = array(
["damskie",     "Akcesoria damskie",   "Czapki damskie",                   "",                                "czapki-damskie"],                                
["damskie",     "Akcesoria damskie",   "Kapelusze damskie",                "",                                "kapelusze-damskie"],                                
["damskie",     "Akcesoria damskie",   "Okulary damskie",                  "",                                "okulary-damskie"],                                
["damskie",     "Akcesoria damskie",   "Paski damskie",                    "",                                "paski-damskie"],                                
["damskie",     "Akcesoria damskie",   "Portfele damskie",                 "",                                "portfele-damskie"],                                
["damskie",     "Akcesoria damskie",   "Rękawiczki damskie",               "",                                "rekawiczki-damskie"],                                
["damskie",     "Akcesoria damskie",   "Szaliki damskie",                  "",                                "szaliki-damskie"],                                
["damskie",     "Akcesoria damskie",   "",                                 "",                                "akcesoria-damskie"],
["damskie",     "Bielizna damska",     "Bielizna nocna",                   "Koszulki nocne",                  "koszulki-nocne"],                  
["damskie",     "Bielizna damska",     "Bielizna nocna",                   "Piżamy damskie",                  "pizamy-damskie"],                  
["damskie",     "Bielizna damska",     "Bielizna nocna",                   "Szlafroki damskie",               "szlafroki-damskie"],               
["damskie",     "Bielizna damska",     "Bielizna nocna",                   "",                                "bielizna-nocna"],
["damskie",     "Bielizna damska",     "Biustonosze",                      "Biustonosze balkonetka",          "biustonosze-balkonetka"],          
["damskie",     "Bielizna damska",     "Biustonosze",                      "Biustonosze bardotki",            "biustonosze-bardotki"],            
["damskie",     "Bielizna damska",     "Biustonosze",                      "Biustonosze koronkowe",           "biustonosze-koronkowe"],           
["damskie",     "Bielizna damska",     "Biustonosze",                      "Biustonosze push up",             "biustonosze-push-up"],             
["damskie",     "Bielizna damska",     "Biustonosze",                      "Biustonosze sportowe",            "biustonosze-sportowe"],            
["damskie",     "Bielizna damska",     "Biustonosze",                      "Biustonosze miękkie",             "biustonosze-miekkie"],             
["damskie",     "Bielizna damska",     "Biustonosze",                      "Biustonosze minimizer",           "biustonosze-minimizer"],           
["damskie",     "Bielizna damska",     "Biustonosze",                      "Biustonosze usztywniane",         "biustonosze-usztywniane"],   
["damskie",     "Bielizna damska",     "Biustonosze",                      "",                                "biustonosze"],      
["damskie",     "Bielizna damska",     "Body damskie",                     "",                                "body-damskie"],                                
["damskie",     "Bielizna damska",     "Gorsety damskie",                  "",                                "gorsety-damskie"],                                
["damskie",     "Bielizna damska",     "Majtki damskie",                   "Bokserki damskie",                "bokserki-damskie"],                
["damskie",     "Bielizna damska",     "Majtki damskie",                   "Figi damskie",                    "figi-damskie"],                    
["damskie",     "Bielizna damska",     "Majtki damskie",                   "Stringi damskie",                 "stringi-damskie"],                 
["damskie",     "Bielizna damska",     "Majtki damskie",                   "",                                "majtki-damskie"],
["damskie",     "Bielizna damska",     "Pasy do pończoch",                 "",                                "pasy-do-ponczoch"],                                
["damskie",     "Bielizna damska",     "Podkolanówki damskie",             "",                                "podkolanowki-damskie"],                                
["damskie",     "Bielizna damska",     "Pończochy damskie",                "",                                "ponczochy-damskie"],                                
["damskie",     "Bielizna damska",     "Skarpetki damskie",                "",                                "skarpetki-damskie"],                                
["damskie",     "Bielizna damska",     "Rajstopy damskie",                 "",                                "rajstopy-damskie"],                                
["damskie",     "Bielizna damska",     "Stroje kąpielowe damskie",         "Bikini",                          "bikini"],                          
["damskie",     "Bielizna damska",     "Stroje kąpielowe damskie",         "Stroje kąpielowe dwuczęściowe",   "stroje-kapielowe-dwuczesciowe"],   
["damskie",     "Bielizna damska",     "Stroje kąpielowe damskie",         "Stroje kąpielowe jednoczęściowe", "stroje-kapielowe-jednoczesciowe"], 
["damskie",     "Bielizna damska",     "Stroje kąpielowe damskie",         "Monokini",                        "monokini"],                        
["damskie",     "Bielizna damska",     "Stroje kąpielowe damskie",         "Tankini",                         "tankini"],                         
["damskie",     "Bielizna damska",     "Stroje kąpielowe damskie",         "",                                "stroje-kapielowe-damskie"],
["damskie",     "Bielizna damska",     "Zakolanówki",                      "",                                "zakolanowki"],                                
["damskie",     "Bielizna damska",     "",                                 "",                                "bielizna-damska"], 
["damskie",     "Biżuteria damska",    "Bransoletki",                      "Bransoletki skórzane",            "bransoletki-skorzane"],            
["damskie",     "Biżuteria damska",    "Bransoletki",                      "Bransoletki swarovski",           "bransoletki-swarovski"],           
["damskie",     "Biżuteria damska",    "Bransoletki",                      "Bransoletki sznurkowe",           "bransoletki-sznurkowe"],           
["damskie",     "Biżuteria damska",    "Bransoletki",                      "",                                "bransoletki"], 
["damskie",     "Biżuteria damska",    "Broszki",                          "",                                "broszki"],                                
["damskie",     "Biżuteria damska",    "Łańcuszki",                        "",                                "lancuszki"],                                
["damskie",     "Biżuteria damska",    "Klipsy",                           "",                                "klipsy"],                                
["damskie",     "Biżuteria damska",    "Naszyjniki",                       "",                                "naszyjniki"],                                
["damskie",     "Biżuteria damska",    "Kolczyki",                         "",                                "kolczyki"],                                
["damskie",     "Biżuteria damska",    "Pierścionki",                      "",                                "pierscionki"],                                
["damskie",     "Biżuteria damska",    "Wisiorki",                         "",                                "wisiorki"],                                
["damskie",     "Biżuteria damska",    "Zawieszki",                        "",                                "zawieszki"],                                
["damskie",     "Biżuteria damska",    "",                                 "",                                "bizuteria-damska"], 
["damskie",     "Bluzki damskie",      "Bluzki koronkowe",                 "",                                "bluzki-koronkowe"],                                
["damskie",     "Bluzki damskie",      "Bluzki oversize",                  "",                                "bluzki-oversize"],                                
["damskie",     "Bluzki damskie",      "Bluzki sportowe",                  "",                                "bluzki-sportowe"],                                
["damskie",     "Bluzki damskie",      "Bluzki wieczorowe",                "",                                "bluzki-wieczorowe"],                                
["damskie",     "Bluzki damskie",      "Bluzki z nadrukiem",               "",                                "bluzki-z-nadrukiem"],                                
["damskie",     "Bluzki damskie",      "",                                 "",                                "bluzki-damskie"],
["damskie",     "Bluzy damskie",       "Bluzy polarowe damskie",           "",                                "bluzy-polarowe-damskie"],                                
["damskie",     "Bluzy damskie",       "Bluzy sportowe damskie",           "",                                "bluzy-sportowe-damskie"],                                
["damskie",     "Bluzy damskie",       "Bluzy z kapturem damskie",         "",                                "bluzy-z-kapturem-damskie"],                    
["damskie",     "Bluzy damskie",       "",                                 "",                                "bluzy-damskie"],            
["damskie",     "Buty damskie",        "Baleriny damskie",                 "Baleriny ażurowe",                "baleriny-azurowe"],                
["damskie",     "Buty damskie",        "Baleriny damskie",                 "Baleriny lakierowane",            "baleriny-lakierowane"],            
["damskie",     "Buty damskie",        "Baleriny damskie",                 "Baleriny na koturnie",            "baleriny-na-koturnie"],            
["damskie",     "Buty damskie",        "Baleriny damskie",                 "Meliski",                         "meliski"],                         
["damskie",     "Buty damskie",        "Baleriny damskie",                 "",                                "baleriny-damskie"],
["damskie",     "Buty damskie",        "Botki damskie",                    "Botki ażurowe",                   "botki-azurowe"],                   
["damskie",     "Buty damskie",        "Botki damskie",                    "Botki na koturnie",               "botki-na-koturnie"],               
["damskie",     "Buty damskie",        "Botki damskie",                    "Botki na obcasie",                "botki-na-obcasie"],                
["damskie",     "Buty damskie",        "Botki damskie",                    "Botki na platformie",             "botki-na-platformie"],             
["damskie",     "Buty damskie",        "Botki damskie",                    "Botki peep toe",                  "botki-peep-toe"],                  
["damskie",     "Buty damskie",        "Botki damskie",                    "Botki sznurowane",                "botki-sznurowane"],                
["damskie",     "Buty damskie",        "Botki damskie",                    "Botki z frędzlami",               "botki-z-fredzlami"],               
["damskie",     "Buty damskie",        "Botki damskie",                    "Botki zamszowe",                  "botki-zamszowe"],                  
["damskie",     "Buty damskie",        "Botki damskie",                    "Botki zimowe",                    "botki-zimowe"],                    
["damskie",     "Buty damskie",        "Botki damskie",                    "",                                "botki-damskie"], 
["damskie",     "Buty damskie",        "Buty sportowe damskie",            "Buty do biegania damskie",        "buty-do-biegania-damskie"],        
["damskie",     "Buty damskie",        "Buty sportowe damskie",            "Buty treningowe damskie",         "buty-treningowe-damskie"],         
["damskie",     "Buty damskie",        "Buty sportowe damskie",            "",                                "buty-sportowe-damskie"], 
["damskie",     "Buty damskie",        "Buty trekkingowe damskie",         "",                                "buty-trekkingowe-damskie"],                                
["damskie",     "Buty damskie",        "Czółenka damskie",                 "Czółenka na koturnie",            "czolenka-na-koturnie"],            
["damskie",     "Buty damskie",        "Czółenka damskie",                 "Czółenka peep toe",               "czolenka-peep-toe"],               
["damskie",     "Buty damskie",        "Czółenka damskie",                 "Czółenka skórzane",               "czolenka-skorzane"],               
["damskie",     "Buty damskie",        "Czółenka damskie",                 "Czółenka zamszowe",               "czolenka-zamszowe"],               
["damskie",     "Buty damskie",        "Czółenka damskie",                 "",                                "czolenka-damskie"],
["damskie",     "Buty damskie",        "Espadryle damskie",                "",                                "espadryle-damskie"],                                
["damskie",     "Buty damskie",        "Kalosze damskie",                  "",                                "kalosze-damskie"],                                
["damskie",     "Buty damskie",        "Kapcie damskie",                   "",                                "kapcie-damskie"],                                
["damskie",     "Buty damskie",        "Klapki damskie",                   "",                                "klapki-damskie"],                                
["damskie",     "Buty damskie",        "Kozaki damskie",                   "Kozaki na obcasie",               "kozaki-na-obcasie"],               
["damskie",     "Buty damskie",        "Kozaki damskie",                   "Kozaki za kolano",                "kozaki-za-kolano"],                
["damskie",     "Buty damskie",        "Kozaki damskie",                   "Kozaki zamszowe",                 "kozaki-zamszowe"],                 
["damskie",     "Buty damskie",        "Kozaki damskie",                   "Muszkieterki",                    "muszkieterki"],                    
["damskie",     "Buty damskie",        "Kozaki damskie",                   "Oficerki damskie",                "oficerki-damskie"],                
["damskie",     "Buty damskie",        "Kozaki damskie",                   "",                                "kozaki-damskie"],
["damskie",     "Buty damskie",        "Lordsy damskie",                   "",                                "lordsy-damskie"],                                
["damskie",     "Buty damskie",        "Półbuty damskie",                  "",                                "polbuty-damskie"],                                
["damskie",     "Buty damskie",        "Szpilki damskie",                  "Szpilki asymetryczne",            "szpilki-asymetryczne"],            
["damskie",     "Buty damskie",        "Szpilki damskie",                  "Szpilki lakierowane",             "szpilki-lakierowane"],             
["damskie",     "Buty damskie",        "Szpilki damskie",                  "Szpilki skórzane",                "szpilki-skorzane"],                
["damskie",     "Buty damskie",        "Szpilki damskie",                  "",                                "szpilki-damskie"],
["damskie",     "Buty damskie",        "Trampki damskie",                  "",                                "trampki-damskie"],                                
["damskie",     "Buty damskie",        "",                                 "",                                "buty-damskie"],
["damskie",     "Dresy damskie",       "",                                 "",                                "dresy-damskie"],                                
["damskie",     "Koszule damskie",     "Koszule w kratę damskie",          "",                                "koszule-w-krate-damskie"],                            
["damskie",     "Koszule damskie",     "",                                 "",                                "koszule-damskie"],      
["damskie",     "Kurtki damskie",      "Kurtki do biegania damskie",       "",                                "kurtki-do-biegania-damskie"],                                
["damskie",     "Kurtki damskie",      "Kurtki pikowane damskie",          "",                                "kurtki-pikowane-damskie"],                                
["damskie",     "Kurtki damskie",      "Kurtki puchowe damskie",           "",                                "kurtki-puchowe-damskie"],                                
["damskie",     "Kurtki damskie",      "Kurtki skórzane damskie",          "",                                "kurtki-skorzane-damskie"],                                
["damskie",     "Kurtki damskie",      "Kurtki sportowe damskie",          "",                                "kurtki-sportowe-damskie"],                                
["damskie",     "Kurtki damskie",      "",                                 "",                                "kurtki-damskie"], 
["damskie",     "Płaszcze damskie",    "Płaszcze oversize",                "",                                "plaszcze-oversize"],                                
["damskie",     "Płaszcze damskie",    "Płaszcze pikowane",                "",                                "plaszcze-pikowane"],                                
["damskie",     "Płaszcze damskie",    "Płaszcze wełniane",                "",                                "plaszcze-welniane"],                                
["damskie",     "Płaszcze damskie",    "Płaszcze z futerkiem",             "",                                "plaszcze-z-futerkiem"],                                
["damskie",     "Płaszcze damskie",    "Płaszcze z kapturem",              "",                                "plaszcze-z-kapturem"],                                
["damskie",     "Płaszcze damskie",    "Płaszcze zimowe",                  "",                                "plaszcze-zimowe"],                                
["damskie",     "Płaszcze damskie",    "",                                 "",                                "plaszcze-damskie"], 
["damskie",     "Spodnie damskie",     "Alladynki damskie",                "",                                "alladynki-damskie"],                                
["damskie",     "Spodnie damskie",     "Chinosy damskie",                  "",                                "chinosy-damskie"],                                
["damskie",     "Spodnie damskie",     "Rybaczki damskie",                 "",                                "rybaczki-damskie"],                                
["damskie",     "Spodnie damskie",     "Spodnie bootcut",                  "",                                "spodnie-bootcut"],                                
["damskie",     "Spodnie damskie",     "Spodnie culotte",                  "",                                "spodnie-culotte"],                                
["damskie",     "Spodnie damskie",     "Spodnie cygaretki",                "",                                "spodnie-cygaretki"],                                
["damskie",     "Spodnie damskie",     "Spodnie dresowe damskie",          "",                                "spodnie-dresowe-damskie"],                                
["damskie",     "Spodnie damskie",     "Spodnie rurki damskie",            "",                                "spodnie-rurki-damskie"],                                
["damskie",     "Spodnie damskie",     "Spodnie skinny",                   "",                                "spodnie-skinny"],                                
["damskie",     "Spodnie damskie",     "Spodnie sportowe damskie",         "",                                "spodnie-sportowe-damskie"],                                
["damskie",     "Spodnie damskie",     "",                                 "",                                "spodnie-damskie"],
["damskie",     "Spódnice",            "Spódnice asymetryczne",            "",                                "spodnice-asymetryczne"],                                
["damskie",     "Spódnice",            "Spódnice jeansowe",                "",                                "spodnice-jeansowe"],                                
["damskie",     "Spódnice",            "Spódnice maxi",                    "",                                "spodnice-maxi"],                                
["damskie",     "Spódnice",            "Spódnice midi",                    "",                                "spodnice-midi"],                                
["damskie",     "Spódnice",            "Spódnice mini",                    "",                                "spodnice-mini"],                                
["damskie",     "Spódnice",            "Spódnice ołówkowe",                "",                                "spodnice-olowkowe"],                                
["damskie",     "Spódnice",            "Spódnice plisowane",               "",                                "spodnice-plisowane"],                                
["damskie",     "Spódnice",            "Spódnice rozkloszowane",           "",                                "spodnice-rozkloszowane"],                                
["damskie",     "Spódnice",            "Spódnice skórzane",                "",                                "spodnice-skorzane"],                                
["damskie",     "Spódnice",            "Spódnice sportowe",                "",                                "spodnice-sportowe"],                                
["damskie",     "Spódnice",            "Spódnice tiulowe",                 "",                                "spodnice-tiulowe"],                                
["damskie",     "Spódnice",            "Spódnice trapezowe",               "",                                "spodnice-trapezowe"],                                
["damskie",     "Spódnice",            "",                                 "",                                "spodnice"],  
["damskie",     "Swetry damskie",      "Długie swetry damskie",            "",                                "dlugie-swetry-damskie"],                                
["damskie",     "Swetry damskie",      "Golfy damskie",                    "",                                "golfy-damskie"],                                
["damskie",     "Swetry damskie",      "Kardigany damskie",                "",                                "kardigany-damskie"],                                
["damskie",     "Swetry damskie",      "Swetry rozpinane damskie",         "",                                "swetry-rozpinane-damskie"],                             
["damskie",     "Swetry damskie",      "",                                 "",                                "swetry-damskie"],   
["damskie",     "Sukienki",            "Sukienki asymetryczne",            "",                                "sukienki-asymetryczne"],                                
["damskie",     "Sukienki",            "Sukienki do pracy",                "",                                "sukienki-do-pracy"],                                
["damskie",     "Sukienki",            "Sukienki dresowe",                 "",                                "sukienki-dresowe"],                                
["damskie",     "Sukienki",            "Sukienki dżinsowe",                "",                                "sukienki-dzinsowe"],                                
["damskie",     "Sukienki",            "Sukienki gorsetowe",               "",                                "sukienki-gorsetowe"],                                
["damskie",     "Sukienki",            "Sukienki koktajlowe",              "",                                "sukienki-koktajlowe"],                                
["damskie",     "Sukienki",            "Sukienki koronkowe",               "",                                "sukienki-koronkowe"],                                
["damskie",     "Sukienki",            "Sukienki koszulowe",               "",                                "sukienki-koszulowe"],                                
["damskie",     "Sukienki",            "Sukienki maxi",                    "",                                "sukienki-maxi"],                                
["damskie",     "Sukienki",            "Sukienki midi",                    "",                                "sukienki-midi"],                                
["damskie",     "Sukienki",            "Sukienki mini",                    "",                                "sukienki-mini"],                                
["damskie",     "Sukienki",            "Sukienki na wesele",               "",                                "sukienki-na-wesele"],                                
["damskie",     "Sukienki",            "Sukienki ołówkowe",                "",                                "sukienki-olowkowe"],                                
["damskie",     "Sukienki",            "Sukienki pastelowe",               "",                                "sukienki-pastelowe"],                                
["damskie",     "Sukienki",            "Sukienki plus size",               "",                                "sukienki-plus-size"],                                
["damskie",     "Sukienki",            "Sukienki rozkloszowane",           "",                                "sukienki-rozkloszowane"],                                
["damskie",     "Sukienki",            "Sukienki sportowe",                "",                                "sukienki-sportowe"],                                
["damskie",     "Sukienki",            "Sukienki trapezowe",               "",                                "sukienki-trapezowe"],                                
["damskie",     "Sukienki",            "Sukienki wieczorowe",              "",                                "sukienki-wieczorowe"],                                
["damskie",     "Sukienki",            "Sukienki wizytowe",                "",                                "sukienki-wizytowe"],                                
["damskie",     "Sukienki",            "Sukienki z cekinami",              "",                                "sukienki-z-cekinami"],                                
["damskie",     "Sukienki",            "Sukienki z frędzlami",             "",                                "sukienki-z-fredzlami"],                                
["damskie",     "Sukienki",            "Sukienki z odkrytymi plecami",     "",                                "sukienki-z-odkrytymi-plecami"],                                
["damskie",     "Sukienki",            "Sukienki za kolano",               "",                                "sukienki-za-kolano"], 
["damskie",     "Sukienki",            "Sukienki na sylwestra",            "",                                "sukienki-na-sylwestra"],
["damskie",     "Sukienki",            "Sukienki letnie",                  "",                                "sukienki-letnie"],
["damskie",     "Sukienki",            "Sukienki na studniówkę",           "",                                "sukienki-na-studniowke"],
["damskie",     "Sukienki",            "Sukienki na komunię",              "",                                "sukienki-na-komunie"],
["damskie",     "Sukienki",            "Sukienki boho",                    "",                                "sukienki-boho"],                               
["damskie",     "Sukienki",            "",                                 "",                                "sukienki"],
["damskie",     "Torebki damskie",     "Kopertówki",                       "",                                "kopertowki"],                                
["damskie",     "Torebki damskie",     "Plecaki damskie",                  "",                                "plecaki-damskie"],                                
["damskie",     "Torebki damskie",     "",                                 "",                                "torebki-damskie"],
["damskie",     "Zegarki damskie",     "",                                 "",                                "zegarki-damskie"],                                
["męskie",      "Akcesoria męskie",    "Czapki męskie",                    "",                                "czapki-meskie"],                                
["męskie",      "Akcesoria męskie",    "Krawaty",                          "",                                "krawaty"],                                
["męskie",      "Akcesoria męskie",    "Muchy męskie",                     "",                                "muchy-meskie"],                                
["męskie",      "Akcesoria męskie",    "Okulary męskie",                   "",                                "okulary-meskie"],                                
["męskie",      "Akcesoria męskie",    "Paski męskie",                     "",                                "paski-meskie"],                                
["męskie",      "Akcesoria męskie",    "Portfele męskie",                  "",                                "portfele-meskie"],                                
["męskie",      "Akcesoria męskie",    "Poszetki",                         "",                                "poszetki"],                                
["męskie",      "Akcesoria męskie",    "",                                 "",                                "akcesoria-meskie"], 
["męskie",      "Bielizna męska",      "Kalesony",                         "",                                "kalesony"],                                
["męskie",      "Bielizna męska",      "Kąpielówki",                       "",                                "kapielowki"],                                
["męskie",      "Bielizna męska",      "Majtki męskie",                    "Bokserki męskie",                 "bokserki-męskie"],                 
["męskie",      "Bielizna męska",      "Majtki męskie",                    "Slipy męskie",                    "slipy-meskie"],                    
["męskie",      "Bielizna męska",      "Majtki męskie",                    "",                                "majtki-meskie"],  
["męskie",      "Bielizna męska",      "Piżamy męskie",                    "",                                "pizamy-meskie"],                                
["męskie",      "Bielizna męska",      "Podkoszulki męskie",               "",                                "podkoszulki-meskie"],                                
["męskie",      "Bielizna męska",      "Skarpetki męskie",                 "",                                "skarpetki-meskie"],                                
["męskie",      "Bielizna męska",      "Szlafroki męskie",                 "",                                "szlafroki-meskie"],                                
["męskie",      "Bielizna męska",      "",                                 "",                                "bielizna-meska"], 
["męskie",      "Buty męskie",         "Buty sportowe męskie",             "Buty do biegania męskie",         "buty-do-biegania-meskie"],         
["męskie",      "Buty męskie",         "Buty sportowe męskie",             "Buty piłkarskie",                 "buty-pilkarskie"],                 
["męskie",      "Buty męskie",         "Buty sportowe męskie",             "",                                "buty-sportowe-meskie"], 
["męskie",      "Buty męskie",         "Buty trekkingowe męskie",          "",                                "buty-trekkingowe-meskie"],                                
["męskie",      "Buty męskie",         "Buty wizytowe męskie",             "",                                "buty-wizytowe-meskie"],                                
["męskie",      "Buty męskie",         "Buty zimowe męskie",               "Botki męskie",                    "botki-meskie"],                    
["męskie",      "Buty męskie",         "Buty zimowe męskie",               "Glany męskie",                    "glany-meskie"],                    
["męskie",      "Buty męskie",         "Buty zimowe męskie",               "Śniegowce męskie",                "sniegowce-meskie"],                
["męskie",      "Buty męskie",         "Buty zimowe męskie",               "Trapery męskie",                  "trapery-meskie"],                  
["męskie",      "Buty męskie",         "Buty zimowe męskie",               "",                                "buty-zimowe-meskie"],
["męskie",      "Buty męskie",         "Espadryle męskie",                 "",                                "espadryle-meskie"],                                
["męskie",      "Buty męskie",         "Kapcie męskie",                    "",                                "kapcie-meskie"],                                
["męskie",      "Buty męskie",         "Klapki męskie",                    "",                                "klapki-meskie"],                                
["męskie",      "Buty męskie",         "Półbuty męskie",                   "Półbuty męskie skórzane",         "polbuty-meskie-skorzane"],         
["męskie",      "Buty męskie",         "Półbuty męskie",                   "Półbuty męskie zamszowe",         "polbuty-meskie-zamszowe"],         
["męskie",      "Buty męskie",         "Półbuty męskie",                   "",                                "polbuty-meskie"],  
["męskie",      "Buty męskie",         "Sandały męskie",                   "Sandały męskie skórzane",         "sandały-meskie-skorzane"],         
["męskie",      "Buty męskie",         "Sandały męskie",                   "Sandały męskie sportowe",         "sandały-meskie-sportowe"],     
["męskie",      "Buty męskie",         "Sandały męskie",                   "",                                "sandały-meskie"],    
["męskie",      "Buty męskie",         "",                                 "",                                "buty-meskie"],  
["męskie",      "Koszule męskie",      "Koszule jeansowe męskie",          "",                                "koszule-jeansowe-meskie"],                                
["męskie",      "Koszule męskie",      "Koszule męskie slim",              "",                                "koszule-meskie-slim"],                                
["męskie",      "Koszule męskie",      "Koszule męskie sportowe",          "",                                "koszule-meskie-sportowe"],                                
["męskie",      "Koszule męskie",      "Koszule w kratę męskie",           "",                                "koszule-w-krate-meskie"],                                
["męskie",      "Koszule męskie",      "",                                 "",                                "koszule-meskie"], 
["męskie",      "Koszulki męskie",     "Koszulki polo męskie",             "",                                "koszulki-polo-meskie"],                                
["męskie",      "Koszulki męskie",     "Koszulki z długim rękawem męskie", "",                                "koszulki-z-dlugim-rekawem-meskie"],                                
["męskie",      "Koszulki męskie",     "T shirty męskie",                  "",                                "t-shirty-meskie"],                                
["męskie",      "Koszulki męskie",     "",                                 "",                                "koszulki-meskie"], 
["męskie",      "Kurtki męskie",       "Kurtki pikowane męskie",           "",                                "kurtki-pikowane-meskie"],                                
["męskie",      "Kurtki męskie",       "Kurtki przejściowe męskie",        "",                                "kurtki-przejsciowe-meskie"],                                
["męskie",      "Kurtki męskie",       "Kurtki puchowe męskie",            "",                                "kurtki-puchowe-meskie"],                                
["męskie",      "Kurtki męskie",       "Kurtki skórzane męskie",           "",                                "kurtki-skorzane-meskie"],                                
["męskie",      "Kurtki męskie",       "Kurtki sportowe męskie",           "",                                "kurtki-sportowe-meskie"],                                
["męskie",      "Kurtki męskie",       "Kurtki zimowe męskie",             "",                                "kurtki-zimowe-meskie"],                                
["męskie",      "Kurtki męskie",       "Parki męskie",                     "",                                "parki-meskie"],                                
["męskie",      "Kurtki męskie",       "",                                 "",                                "kurtki-meskie"],    
["męskie",      "Spodnie męskie",      "Spodnie dresowe męskie",           "",                                "spodnie-dresowe-meskie"],                                
["męskie",      "Spodnie męskie",      "",                                 "",                                "spodnie-meskie"],   
["męskie",      "Torby męskie",        "Plecaki męskie",                   "",                                "plecaki-meskie"],                                
["męskie",      "Torby męskie",        "Teczki męskie",                    "",                                "teczki-meskie"],                                
["męskie",      "Torby męskie",        "Torby męskie na ramię",            "",                                "torby-meskie-na-ramie"],                                
["męskie",      "Torby męskie",        "Torby skórzane męskie",            "",                                "torby-skorzane-meskie"],                                
["męskie",      "Torby męskie",        "Torby sportowe męskie",            "",                                "torby-sportowe-meskie"],                                
["męskie",      "Torby męskie",        "",                                 "",                                "torby-meskie"],    
["męskie",      "Zegarki męskie",      "",                                 "",                                "zegarki-meskie"],                                
["dla dziecka", "Buty dziecięce",      "Buty sportowe dziecięce",          "Buty sportowe chłopięce",         "buty-sportowe-chlopiece"],         
["dla dziecka", "Buty dziecięce",      "Buty sportowe dziecięce",          "Buty sportowe dziewczęce",        "buty-sportowe-dziewczece"],        
["dla dziecka", "Buty dziecięce",      "Buty sportowe dziecięce",          "",                                "buty-sportowe-dzieciece"], 
["dla dziecka", "Buty dziecięce",      "Kalosze dziecięce",                "Kalosze chłopięce",               "kalosze-chlopiece"],               
["dla dziecka", "Buty dziecięce",      "Kalosze dziecięce",                "Kalosze dziewczęce",              "kalosze-dziewczece"],              
["dla dziecka", "Buty dziecięce",      "Kalosze dziecięce",                "",                                "kalosze-dzieciece"], 
["dla dziecka", "Buty dziecięce",      "Półbuty dziecięce",                "Półbuty chłopięce",               "polbuty-chlopiece"],                
["dla dziecka", "Buty dziecięce",      "Półbuty dziecięce",                "Półbuty dziewczęce",              "polbuty-dziewczece"],              
["dla dziecka", "Buty dziecięce",      "Półbuty dziecięce",                "",                                "polbuty-dzieciece"], 
["dla dziecka", "Buty dziecięce",      "Sandały dziecięce",                "",                                "sandaly-dzieciece"],                                
["dla dziecka", "Buty dziecięce",      "Trampki dziecięce",                "Trampki chłopięce",               "trampki-chlopiece"],               
["dla dziecka", "Buty dziecięce",      "Trampki dziecięce",                "Trampki dziewczęce",              "trampki-dziewczece"],              
["dla dziecka", "Buty dziecięce",      "Trampki dziecięce",                "",                                "trampki-dzieciece"],   
["dla dziecka", "Buty dziecięce",      "",                                 "",                                "buty-dzieciece"],  
["dla dziecka", "Kurtki dziecięce",    "Kurtki chłopięce",                 "",                                "kurtki-chlopiece"],                                
["dla dziecka", "Kurtki dziecięce",    "Kurtki dziewczęce",                "",                                "kurtki-dziewczece"],                                
["dla dziecka", "Kurtki dziecięce",    "",                                 "",                                "kurtki-dzieciece"], 
["dla dziecka", "Spodnie dziecięce",   "Spodnie chłopięce",                "",                                "spodnie-chlopiece"],                                
["dla dziecka", "Spodnie dziecięce",   "Spodnie dziewczęce",               "",                                "spodnie-dziewczece"], 
["dla dziecka", "Spodnie dziecięce",   "",                                 "",                                "spodnie-dzieciece"], 
["dla dziecka", "Sukienki dziewczęce", "",                                 "",                                "sukienki-dziewczece"]                                               
);

$count_top = count($nawigacja_kategoria);

for($i=1;$i<=$count_top;$i++) {

	$nawigacjaKategoriaTop = $nawigacja_kategoria[$i-1][0];
	$nawigacjaKategoriaMaincategory = $nawigacja_kategoria[$i-1][1];
	$nawigacjaKategoriaCategoryOne = $nawigacja_kategoria[$i-1][2];
	$nawigacjaKategoriaSubcategoryOne = $nawigacja_kategoria[$i-1][3];
	$nawigacjaKategoriaAlias = $nawigacja_kategoria[$i-1][4];

	$sql = "INSERT INTO `jos_nawigacja_kategoria` (`nawigacja_kategoria_top`, `nawigacja_kategoria_maincategory`, `nawigacja_kategoria_categoryOne`, `nawigacja_kategoria_subcategoryOne`, `nawigacja_kategoria_alias`)"
	."VALUES ('$nawigacjaKategoriaTop', '$nawigacjaKategoriaMaincategory', '$nawigacjaKategoriaCategoryOne', '$nawigacjaKategoriaSubcategoryOne', '$nawigacjaKategoriaAlias')"
	;
	$result = mysql_query($sql);
}
