<?php
error_reporting(0);
$com=mysql_connect("localhost", "u705076634_longfash" ,"Dds76sd67gdcg");
mysql_set_charset('utf8',$com);
mysql_select_db("u705076634_longfash", $com) or die(mysql_error());

// a
/*$noindexValues = '/Sukienki/dlugie/|/Sukienki/srednie/|/Sukienki/krotkie/|/Sukienki-asymetryczne/srednie/|/Sukienki-do-pracy/dlugie/|/Sukienki-do-pracy/srednie/|/Sukienki-dresowe/srednie/|/Sukienki-maxi/dlugie/|/Sukienki-midi/srednie/|/Sukienki-mini/krotkie/|
/Sukienki-olowkowe/srednie/|/Sukienki-olowkowe/krotkie/|/Sukienki-rozkloszowane/srednie/|/Sukienki-rozkloszowane/krotkie/|/Sukienki-trapezowe/krotkie/|/Sukienki-wieczorowe/dlugie/|/Sukienki-wizytowe/dlugie/|/Sukienki-wizytowe/srednie/|
/Sukienki-wizytowe/krotkie/|/Sukienki/z-dlugim-rekawem/|/Sukienki/z-krotkim-rekawem/|/Sukienki/bez-rekawa/|/Sukienki-do-pracy/z-krotkim-rekawem/|/Sukienki-midi/bez-rekawa/|/Sukienki-olowkowe/bez-rekawa/|/Sukienki-rozkloszowane/z-krotkim-rekawem/|
/Sukienki-rozkloszowane/bez-rekawa/|/Sukienki-wizytowe/z-dlugim-rekawem/|/Sukienki-wizytowe/z-krotkim-rekawem/|/Sukienki-wizytowe/bez-rekawa/|/Akcesoria-damskie/czarne/|/Akcesoria-damskie/czerwone/|/Akcesoria-damskie/brazowe/|
/Akcesoria-damskie/niebieskie/|/Akcesoria-damskie/rozowe/|/Akcesoria-damskie/zielone/|/Akcesoria-meskie/czarne/|/Akcesoria-meskie/czerwone/|/Akcesoria-meskie/granatowe/|/Akcesoria-meskie/brazowe/|/Akcesoria-meskie/szare/|
/Bielizna-damska/biale/|/Bielizna-damska/czarne/|/Bielizna-damska/czerwone/|/Bielizna-damska/granatowe/|/Bielizna-damska/bezowe/|/Bielizna-damska/bordowe/|/Bielizna-damska/blekitne/|/Bielizna-damska/mietowe/|/Bielizna-damska/niebieskie/|
/Bielizna-damska/rozowe/|/Bielizna-damska/szare/|/Bielizna-damska/turkusowe/|/Bielizna-damska/zielone/|/Bielizna-damska/zolte/|/Bielizna-meska/biale/|/Bielizna-meska/czarne/|/Bielizna-meska/czerwone/|/Bielizna-meska/granatowe/|
/Bielizna-meska/niebieskie/|/Bielizna-meska/szare/|/Bizuteria-damska/biale/|/Bizuteria-damska/czarne/|/Bizuteria-damska/czerwone/|/Bizuteria-damska/bezowe/|/Bizuteria-damska/brazowe/|/Bizuteria-damska/fioletowe/|/Bizuteria-damska/niebieskie/|
/Bizuteria-damska/rozowe/|/Bizuteria-damska/srebrne/|/Bizuteria-damska/szare/|/Bizuteria-damska/turkusowe/|/Bizuteria-damska/wielokolorowe/|/Bizuteria-damska/zielone/|/Bizuteria-damska/zolte/|/Bizuteria-damska/zlote/|/Bluzki-damskie/biale/|
/Bluzki-damskie/czarne/|/Buty-damskie/czarne/|/Koszulki-meskie/biale/|/Koszulki-meskie/czarne/|/Koszulki-meskie/czerwone/|/Koszulki-meskie/granatowe/|/Plaszcze-damskie/czarne/|/Spodnice/czarne/|/Spodnice/czerwone/|/Spodnice/granatowe/|
/Spodnice/bezowe/|/Spodnice/rozowe/|/Spodnice/szare/|/Spodnie-damskie/czarne/|/Spodnie-damskie/niebieskie/|/Sukienki/biale/|/Sukienki/czarne/|/Sukienki/czerwone/|/Sukienki/granatowe/|/Sukienki/bezowe/|/Sukienki/bordowe/|/Sukienki/brazowe/|
/Sukienki/blekitne/|/Sukienki/mietowe/|/Sukienki/niebieskie/|/Sukienki/rozowe/|/Sukienki/szare/|/Sukienki/zielone/|/Sukienki/zolte/|/Torby-meskie/czarne/|/Torby-meskie/brazowe/|/Torebki-damskie/czarne/|/Torebki-damskie/szare/|
/Zegarki-damskie/czarne/|/Zegarki-meskie/czarne/|/Bielizna-nocna/biale/|/Bielizna-nocna/czarne/|/Bielizna-nocna/czerwone/|/Bielizna-nocna/granatowe/|/Bielizna-nocna/bordowe/|/Bielizna-nocna/rozowe/|/Bielizna-nocna/szare/|/Biustonosze/biale/|
/Biustonosze/czarne/|/Biustonosze/czerwone/|/Biustonosze/bezowe/|/Biustonosze/niebieskie/|/Biustonosze/rozowe/|/Biustonosze/szare/|/Body-damskie/czarne/|/Bojowki-damskie/niebieskie/|/Bransoletki/biale/|/Bransoletki/czarne/|
/Bransoletki/czerwone/|/Bransoletki/rozowe/|/Bransoletki/srebrne/|/Bransoletki/zielone/|/Bransoletki/zolte/|/Bransoletki/zlote/|/Kapielowki/czarne/|/Kolczyki/biale/|/Kolczyki/czarne/|/Kolczyki/czerwone/|/Kolczyki/rozowe/|/Kolczyki/srebrne/|
/Kolczyki/zolte/|/Kolczyki/zlote/|/Lancuszki/srebrne/|/Lancuszki/zolte/|/Majtki-damskie/biale/|/Majtki-damskie/czarne/|/Majtki-damskie/czerwone/|/Majtki-damskie/bezowe/|/Majtki-meskie/biale/|/Majtki-meskie/czarne/|/Majtki-meskie/czerwone/|
/Majtki-meskie/granatowe/|/Majtki-meskie/niebieskie/|/Majtki-meskie/szare/|/Naszyjniki/biale/|/Naszyjniki/czarne/|/Naszyjniki/rozowe/|/Naszyjniki/srebrne/|/Naszyjniki/zolte/|/Naszyjniki/zlote/|/Okulary-damskie/czarne/|/Okulary-meskie/czarne/|
/Pierscionki/biale/|/Pierscionki/czarne/|/Pierscionki/rozowe/|/Pierscionki/srebrne/|/Pierscionki/zolte/|/Plecaki-damskie/czarne/|/Portfele-damskie/czarne/|/Portfele-damskie/czerwone/|/Portfele-damskie/brazowe/|/Portfele-damskie/niebieskie/|
/Portfele-damskie/rozowe/|/Portfele-damskie/zielone/|/Portfele-meskie/czarne/|/Portfele-meskie/czerwone/|/Portfele-meskie/granatowe/|/Portfele-meskie/brazowe/|/Spodnice-olowkowe/czarne/|/Spodnice-olowkowe/szare/|/Spodnice-rozkloszowane/czarne/|
/Stroje-kapielowe-damskie/biale/|/Stroje-kapielowe-damskie/czarne/|/Stroje-kapielowe-damskie/niebieskie/|/Stroje-kapielowe-damskie/rozowe/|/Sukienki-asymetryczne/czarne/|/Sukienki-asymetryczne/czerwone/|/Sukienki-asymetryczne/granatowe/|
/Sukienki-asymetryczne/rozowe/|/Sukienki-asymetryczne/szare/|/Sukienki-do-pracy/biale/|/Sukienki-do-pracy/czarne/|/Sukienki-do-pracy/czerwone/|/Sukienki-do-pracy/niebieskie/|/Sukienki-do-pracy/rozowe/|/Sukienki-do-pracy/zielone/|
/Sukienki-dresowe/czarne/|/Sukienki-dresowe/szare/|/Sukienki-dzinsowe/niebieskie/|/Sukienki-koktajlowe/czarne/|/Sukienki-koronkowe/czarne/|/Sukienki-koronkowe/rozowe/|/Sukienki-koszulowe/czarne/|/Sukienki-maxi/czarne/|/Sukienki-midi/czarne/|
/Sukienki-midi/czerwone/|/Sukienki-midi/granatowe/|/Sukienki-midi/bezowe/|/Sukienki-midi/niebieskie/|/Sukienki-midi/rozowe/|/Sukienki-midi/szare/|/Sukienki-midi/zielone/|/Sukienki-mini/czarne/|/Sukienki-mini/czerwone/|/Sukienki-mini/granatowe/|
/Sukienki-mini/bezowe/|/Sukienki-mini/szare/|/Sukienki-olowkowe/czarne/|/Sukienki-olowkowe/czerwone/|/Sukienki-olowkowe/granatowe/|/Sukienki-olowkowe/rozowe/|/Sukienki-olowkowe/szare/|/Sukienki-olowkowe/zielone/|/Sukienki-rozkloszowane/biale/|
/Sukienki-rozkloszowane/czarne/|/Sukienki-rozkloszowane/czerwone/|/Sukienki-rozkloszowane/granatowe/|/Sukienki-rozkloszowane/bezowe/|/Sukienki-rozkloszowane/bordowe/|/Sukienki-rozkloszowane/niebieskie/|/Sukienki-rozkloszowane/rozowe/|
/Sukienki-rozkloszowane/szare/|/Sukienki-rozkloszowane/zielone/|/Sukienki-sportowe/czarne/|/Sukienki-sportowe/szare/|/Sukienki-trapezowe/czarne/|/Sukienki-trapezowe/czerwone/|/Sukienki-trapezowe/granatowe/|/Sukienki-trapezowe/rozowe/|
/Sukienki-trapezowe/szare/|/Sukienki-wieczorowe/czarne/|/Sukienki-wieczorowe/czerwone/|/Sukienki-wieczorowe/granatowe/|/Sukienki-wieczorowe/bordowe/|/Sukienki-wieczorowe/rozowe/|/Sukienki-wizytowe/biale/|/Sukienki-wizytowe/czarne/|
/Sukienki-wizytowe/czerwone/|/Sukienki-wizytowe/granatowe/|/Sukienki-wizytowe/bezowe/|/Sukienki-wizytowe/bordowe/|/Sukienki-wizytowe/brazowe/|/Sukienki-wizytowe/blekitne/|/Sukienki-wizytowe/niebieskie/|/Sukienki-wizytowe/rozowe/|
/Sukienki-wizytowe/szare/|/Sukienki-wizytowe/zielone/|/Sukienki-wizytowe/zolte/|/Sukienki-z-cekinami/czarne/|/T-shirty-meskie/biale/|/T-shirty-meskie/czarne/|/T-shirty-meskie/czerwone/|/T-shirty-meskie/granatowe/|/Teczki-meskie/czarne/|
/Torby-skorzane-meskie/czarne/|/Torby-skorzane-meskie/brazowe/|/Wisiorki/biale/|/Wisiorki/srebrne/|/Wisiorki/zolte/|/Zawieszki/biale/|/Zawieszki/czarne/|/Zawieszki/rozowe/|/Zawieszki/srebrne/|/Zawieszki/zolte/|/Bikini/biale/|/Bikini/czarne/|
/Bikini/niebieskie/|/Biustonosze-koronkowe/biale/|/Biustonosze-koronkowe/czarne/|/Biustonosze-koronkowe/bezowe/|/Biustonosze-koronkowe/niebieskie/|/Biustonosze-koronkowe/rozowe/|/Biustonosze-minimizer/biale/|/Biustonosze-minimizer/czarne/|
/Biustonosze-usztywniane/biale/|/Biustonosze-usztywniane/czarne/|/Bokserki-meskie/czarne/|/Bokserki-meskie/granatowe/|/Bokserki-meskie/szare/|/Figi-damskie/biale/|/Figi-damskie/czarne/|/Figi-damskie/czerwone/|/Figi-damskie/bezowe/|
/Koszulki-nocne/biale/|/Koszulki-nocne/czarne/|/Koszulki-nocne/czerwone/|/Koszulki-nocne/granatowe/|/Koszulki-nocne/rozowe/|/Koszulki-nocne/szare/|/Pizamy-damskie/granatowe/|/Pizamy-damskie/rozowe/|/Pizamy-damskie/szare/|/Slipy-meskie/biale/|
/Slipy-meskie/czarne/|/Slipy-meskie/granatowe/|/Stringi-damskie/biale/|/Szlafroki-damskie/czarne/|/Tankini/biale/|/Tankini/czarne/|/Akcesoria-damskie/4u-cavaldi/|/Akcesoria-damskie/arctica/|/Akcesoria-damskie/art/|/Akcesoria-damskie/e-zegarki/|
/Akcesoria-damskie/kamea/|/Akcesoria-damskie/lorenti/|/Akcesoria-damskie/milano-design/|/Akcesoria-damskie/montana/|/Akcesoria-damskie/rovicky/|/Akcesoria-damskie/valentini/|/Akcesoria-meskie/always-wild/|/Akcesoria-meskie/arctica/|
/Akcesoria-meskie/br-drene/|/Akcesoria-meskie/buffalo-wild/|/Akcesoria-meskie/draco/|/Akcesoria-meskie/e-zegarki/|/Akcesoria-meskie/lozano/|/Akcesoria-meskie/montana/|/Akcesoria-meskie/pierre-andreus/|/Akcesoria-meskie/polarized/|
/Akcesoria-meskie/rovicky/|/Akcesoria-meskie/samsonite/|/Akcesoria-meskie/solier/|/Akcesoria-meskie/stylion/|/Akcesoria-meskie/sunoptic/|/Akcesoria-meskie/valentini/|/Bielizna-damska/anais/|/Bielizna-damska/aruelle/|/Bielizna-damska/atlantic/|
/Bielizna-damska/ava/|/Bielizna-damska/ava-lingerie/|/Bielizna-damska/axami/|/Bielizna-damska/babell/|/Bielizna-damska/babella/|/Bielizna-damska/betina/|/Bielizna-damska/cana/|/Bielizna-damska/cornette/|
/Bielizna-damska/de-lafense/|/Bielizna-damska/dkaren/|/Bielizna-damska/donella/|/Bielizna-damska/donna/|/Bielizna-damska/eldar/|/Bielizna-damska/emili/|/Bielizna-damska/eso-hen/|/Bielizna-damska/esotiq/|/Bielizna-damska/esotiq-henderson/|
/Bielizna-damska/ewana/|/Bielizna-damska/figl/|/Bielizna-damska/fiore/|/Bielizna-damska/gabidar/|/Bielizna-damska/gabriella/|/Bielizna-damska/gaia/|/Bielizna-damska/gatta/|/Bielizna-damska/gorsenia/|/Bielizna-damska/gorteks/|
/Bielizna-damska/henderson-ladies/|/Bielizna-damska/irall/|/Bielizna-damska/italian-fashion/|/Bielizna-damska/julimex/|/Bielizna-damska/kabak/|/Bielizna-damska/key/|/Bielizna-damska/kinga/|/Bielizna-damska/konrad/|/Bielizna-damska/l-l/|
/Bielizna-damska/lama/|/Bielizna-damska/leinle/|/Bielizna-damska/livco-corsetti/|/Bielizna-damska/livia-corsetti/|/Bielizna-damska/luna/|/Bielizna-damska/lupo-line/|/Bielizna-damska/marko/|/Bielizna-damska/mat/|/Bielizna-damska/mitex/|
/Bielizna-damska/modo/|/Bielizna-damska/mona/|/Bielizna-damska/nipplex/|/Bielizna-damska/obsessive/|/Bielizna-damska/regina/|/Bielizna-damska/rossli/|/Bielizna-damska/roza/|/Bielizna-damska/self/|/Bielizna-damska/sensis/|
/Bielizna-damska/sesto-senso/|/Bielizna-damska/shepa/|/Bielizna-damska/taro/|/Bielizna-damska/vena/|/Bielizna-damska/veneziana/|/Bielizna-damska/wol-bar/|/Bielizna-damska/wolbar/|/Bielizna-meska/alpha-male/|/Bielizna-meska/atlantic/|
/Bielizna-meska/cornette/|/Bielizna-meska/de-lafense/|/Bielizna-meska/eso-hen/|/Bielizna-meska/henderson/|/Bielizna-meska/key/|/Bielizna-meska/lama/|/Bielizna-meska/luna/|/Bielizna-meska/pierre-cardin/|/Bielizna-meska/regina/|
/Bielizna-meska/rossli/|/Bielizna-meska/sesto-senso/|/Bielizna-meska/shepa/|/Bielizna-meska/spox-sox/|/Bielizna-meska/taro/|/Bielizna-meska/umbro/|/Bizuteria-damska/anemon-atelier/|/Bizuteria-damska/be-the-one/|
/Bizuteria-damska/bizuteria-z-talerzy/|/Bizuteria-damska/boske/|/Bizuteria-damska/by-milla/|/Bizuteria-damska/cloe/|/Bizuteria-damska/coconut-jewellery/|/Bizuteria-damska/czaki-bransoletki/|/Bizuteria-damska/elemthebrand/|
/Bizuteria-damska/eminence/|/Bizuteria-damska/energetix-niemcy/|/Bizuteria-damska/exclusive-by-milla/|/Bizuteria-damska/grol-jewellery/|/Bizuteria-damska/hellaclay/|/Bizuteria-damska/iloko/|
/Bizuteria-damska/kaktusia/|/Bizuteria-damska/lei-handmade/|/Bizuteria-damska/lemon-lovely/|/Bizuteria-damska/luo/|/Bizuteria-damska/maanuela/|/Bizuteria-damska/magneska/|/Bizuteria-damska/mariaela/|/Bizuteria-damska/mazuni/|
/Bizuteria-damska/milita-nikonorov/|/Bizuteria-damska/miss-glow/|/Bizuteria-damska/modelinova/|/Bizuteria-damska/mona/|/Bizuteria-damska/muamua-design/|/Bizuteria-damska/myness/|/Bizuteria-damska/no-logo/|/Bizuteria-damska/olga-zielinska/|
/Bizuteria-damska/polly-design/|/Bizuteria-damska/sentiell/|/Bizuteria-damska/shambala/|/Bizuteria-damska/sotho/|/Bizuteria-damska/staviori/|/Bizuteria-damska/staviori-wlochy/|/Bizuteria-damska/vander-jewelry/|/Bizuteria-damska/venus-galeria/|
/Bizuteria-damska/wec-twoj-jubiler/|/Bizuteria-damska/yenoo/|/Bluzki-damskie/eldar/|/Koszulki-meskie/koszulk/|/Spodnice/figl/|
/Spodnice/katrus/|/Spodnice/lanti/|/Spodnice/moe/|/Spodnice/moremoi/|/Spodnice/nife/|/Spodnice/nommo/|/Spodnice/tessita/|/Sukienki/awama/|/Sukienki/dursi/|/Sukienki/eva-lola/|
/Sukienki/figl/|/Sukienki/fobya/|/Sukienki/freeshion/|/Sukienki/imesia/|/Sukienki/infinite-you/|/Sukienki/ivon/|/Sukienki/katrus/|/Sukienki/lanti/|/Sukienki/lemoniade/|/Sukienki/lou-lou/|/Sukienki/makadamia/|/Sukienki/makeover/|
/Sukienki/merribel/|/Sukienki/milita-nikonorov/|/Sukienki/moe/|/Sukienki/moremoi/|/Sukienki/nife/|/Sukienki/nommo/|/Sukienki/numoco/|/Sukienki/pawelkuzik/|/Sukienki/sale/|/Sukienki/soky-soka/|/Sukienki/tessita/|/Torby-meskie/always-wild/|
/Torby-meskie/br-drene/|/Torby-meskie/mcklein/|/Torby-meskie/paolo-peruzzi/|/Torby-meskie/solier/|/Torebki-damskie/felice/|/Torebki-damskie/rovicky/|/Zegarki-damskie/geneva/|/Zegarki-damskie/no-logo/|/Zegarki-meskie/geneva/|
/Zegarki-meskie/skmei/|/Bielizna-nocna/anais/|/Bielizna-nocna/aruelle/|/Bielizna-nocna/babell/|/Bielizna-nocna/babella/|/Bielizna-nocna/betina/|/Bielizna-nocna/cana/|/Bielizna-nocna/cornette/|
/Bielizna-nocna/de-lafense/|/Bielizna-nocna/dkaren/|/Bielizna-nocna/donna/|/Bielizna-nocna/eldar/|/Bielizna-nocna/eso-hen/|/Bielizna-nocna/gorsenia/|/Bielizna-nocna/henderson-ladies/|/Bielizna-nocna/irall/|/Bielizna-nocna/italian-fashion/|
/Bielizna-nocna/key/|/Bielizna-nocna/l-l/|/Bielizna-nocna/leinle/|/Bielizna-nocna/livco-corsetti/|/Bielizna-nocna/luna/|/Bielizna-nocna/lupo-line/|/Bielizna-nocna/nipplex/|/Bielizna-nocna/nipplex-by-night/|/Bielizna-nocna/regina/|
/Bielizna-nocna/rossli/|/Bielizna-nocna/sensis/|/Bielizna-nocna/taro/|/Biustonosze/ava/|/Biustonosze/ava-lingerie/|/Biustonosze/axami/|/Biustonosze/gaia/|/Biustonosze/gorsenia/|/Biustonosze/gorteks/|/Biustonosze/julimex/|
/Biustonosze/kinga/|/Biustonosze/konrad/|/Biustonosze/lupo-line/|/Biustonosze/mat/|/Biustonosze/nipplex/|/Biustonosze/vena/|/Body-damskie/eldar/|/Body-damskie/figl/|/Body-damskie/mitex/|
/Bransoletki/cloe/|/Bransoletki/energetix-niemcy/|/Bransoletki/iloko/|/Bransoletki/lei-handmade/|/Bransoletki/luo/|/Bransoletki/magneska/|/Bransoletki/mona/|/Bransoletki/myness/|
/Bransoletki/sentiell/|/Bransoletki/yenoo/|/Broszki/elemthebrand/|/Czapki-damskie/kamea/|/Kapielowki/alpha-male/|/Kapielowki/henderson/|/Kapielowki/shepa/|/Kolczyki/anemon-atelier/|
/Kolczyki/bizuteria-z-talerzy/|/Kolczyki/cloe/|/Kolczyki/hellaclay/|/Kolczyki/iloko/|/Kolczyki/luo/|/Kolczyki/maanuela/|/Kolczyki/mazuni/|/Kolczyki/modelinova/|/Kolczyki/mona/|/Kolczyki/myness/|/Kolczyki/no-logo/|
/Kolczyki/olga-zielinska/|/Kolczyki/sentiell/|/Kolczyki/shambala/|/Kolczyki/sotho/|/Kolczyki/staviori-wlochy/|/Kolczyki/wec-twoj-jubiler/|/Kolczyki/yenoo/|/Kopertowki/felice/|/Kopertowki/rovicky/|/Lancuszki/sentiell/|
/Lancuszki/staviori-wlochy/|/Majtki-damskie/atlantic/|/Majtki-damskie/ava/|/Majtki-damskie/babell/|/Majtki-damskie/donella/|/Majtki-damskie/eldar/|/Majtki-damskie/emili/|/Majtki-damskie/ewana/|/Majtki-damskie/gabidar/|
/Majtki-damskie/gaia/|/Majtki-damskie/gorsenia/|/Majtki-damskie/gorteks/|/Majtki-damskie/julimex/|/Majtki-damskie/key/|/Majtki-damskie/kinga/|/Majtki-damskie/lama/|/Majtki-damskie/lupo-line/|/Majtki-damskie/mat/|/Majtki-damskie/mitex/|
/Majtki-damskie/modo/|/Majtki-damskie/nipplex/|/Majtki-damskie/roza/|/Majtki-damskie/vena/|/Majtki-damskie/wol-bar/|/Majtki-damskie/wolbar/|/Majtki-meskie/atlantic/|/Majtki-meskie/cornette/|/Majtki-meskie/henderson/|/Majtki-meskie/key/|
/Majtki-meskie/lama/|/Majtki-meskie/pierre-cardin/|/Majtki-meskie/rossli/|/Majtki-meskie/sesto-senso/|/Majtki-meskie/umbro/|/Naszyjniki/anemon-atelier/|/Naszyjniki/by-milla/|/Naszyjniki/cloe/|/Naszyjniki/iloko/|
/Naszyjniki/luo/|/Naszyjniki/milita-nikonorov/|/Naszyjniki/mona/|/Naszyjniki/myness/|/Naszyjniki/sentiell/|/Naszyjniki/sotho/|/Naszyjniki/staviori-wlochy/|/Okulary-damskie/arctica/|/Okulary-damskie/montana/|/Okulary-meskie/arctica/|
/Okulary-meskie/draco/|/Okulary-meskie/lozano/|/Okulary-meskie/montana/|/Okulary-meskie/polarized/|/Okulary-meskie/stylion/|/Okulary-meskie/sunoptic/|/Paski-damskie/e-zegarki/|/Paski-damskie/rovicky/|/Paski-meskie/br-drene/|
/Paski-meskie/e-zegarki/|/Paski-meskie/solier/|/Pasy-do-ponczoch/julimex/|/Pierscionki/eminence/|/Pierscionki/mona/|/Pierscionki/sentiell/|/Pierscionki/staviori-wlochy/|/Pierscionki/wec-twoj-jubiler/|
/Pizamy-meskie/cornette/|/Pizamy-meskie/henderson/|/Pizamy-meskie/key/|/Pizamy-meskie/luna/|/Pizamy-meskie/regina/|/Pizamy-meskie/rossli/|/Pizamy-meskie/taro/|/Ponczochy-damskie/fiore/|/Ponczochy-damskie/gabriella/|
/Ponczochy-damskie/gatta/|/Ponczochy-damskie/veneziana/|/Portfele-damskie/4u-cavaldi/|/Portfele-damskie/lorenti/|/Portfele-damskie/milano-design/|/Portfele-damskie/producent-niezdefiniowany/|/Portfele-damskie/rovicky/|/Portfele-damskie/valentini/|
/Portfele-meskie/always-wild/|/Portfele-meskie/br-drene/|/Portfele-meskie/buffalo-wild/|/Portfele-meskie/pierre-andreus/|/Portfele-meskie/rovicky/|/Portfele-meskie/samsonite/|/Portfele-meskie/solier/|/Portfele-meskie/valentini/|
/Rajstopy-damskie/fiore/|/Rajstopy-damskie/gabriella/|/Rajstopy-damskie/gatta/|/Rajstopy-damskie/knittex/|/Rajstopy-damskie/livco-corsetti/|/Rajstopy-damskie/mona/|/Rajstopy-damskie/sesto-senso/|/Rajstopy-damskie/veneziana/|
/Skarpetki-damskie/kabak/|/Skarpetki-meskie/spox-sox/|/Spodnice-mini/ivon/|/Spodnice-olowkowe/figl/|/Spodnice-olowkowe/moe/|/Spodnice-olowkowe/moremoi/|/Spodnice-olowkowe/nife/|/Spodnice-rozkloszowane/nife/|
/Stroje-kapielowe-damskie/marko/|/Stroje-kapielowe-damskie/self/|/Stroje-kapielowe-damskie/shepa/|/Sukienki-asymetryczne/katrus/|
/Sukienki-asymetryczne/makadamia/|/Sukienki-asymetryczne/moe/|/Sukienki-asymetryczne/nommo/|/Sukienki-asymetryczne/numoco/|/Sukienki-do-pracy/moremoi/|/Sukienki-dresowe/makadamia/|
/Sukienki-dresowe/moe/|/Sukienki-dresowe/tessita/|/Sukienki-dzinsowe/numoco/|/Sukienki-koktajlowe/nommo/|/Sukienki-koronkowe/nommo/|/Sukienki-koronkowe/numoco/|
/Sukienki-maxi/makadamia/|/Sukienki-maxi/numoco/|/Sukienki-midi/awama/|/Sukienki-midi/figl/|/Sukienki-midi/freeshion/|/Sukienki-midi/katrus/|/Sukienki-midi/makadamia/|/Sukienki-midi/moe/|/Sukienki-midi/moremoi/|
/Sukienki-midi/nife/|/Sukienki-midi/nommo/|/Sukienki-midi/numoco/|/Sukienki-mini/awama/|/Sukienki-mini/dursi/|/Sukienki-mini/ivon/|/Sukienki-mini/moe/|/Sukienki-mini/nommo/|/Sukienki-mini/numoco/|/Sukienki-na-wesele/numoco/|
/Sukienki-olowkowe/dursi/|/Sukienki-olowkowe/ivon/|/Sukienki-olowkowe/merribel/|/Sukienki-olowkowe/moe/|/Sukienki-olowkowe/nife/|/Sukienki-olowkowe/nommo/|/Sukienki-olowkowe/numoco/|/Sukienki-plus-size/nommo/|/Sukienki-rozkloszowane/awama/|
/Sukienki-rozkloszowane/figl/|/Sukienki-rozkloszowane/katrus/|/Sukienki-rozkloszowane/lemoniade/|/Sukienki-rozkloszowane/makadamia/|/Sukienki-rozkloszowane/merribel/|/Sukienki-rozkloszowane/moe/|
/Sukienki-rozkloszowane/moremoi/|/Sukienki-rozkloszowane/nife/|/Sukienki-rozkloszowane/nommo/|/Sukienki-rozkloszowane/numoco/|/Sukienki-rozkloszowane/tessita/|/Sukienki-sportowe/moe/|/Sukienki-sportowe/numoco/|/Sukienki-trapezowe/awama/|
/Sukienki-trapezowe/ivon/|/Sukienki-trapezowe/lemoniade/|/Sukienki-trapezowe/makadamia/|/Sukienki-trapezowe/moe/|/Sukienki-trapezowe/nommo/|/Sukienki-trapezowe/numoco/|/Sukienki-wieczorowe/dursi/|
/Sukienki-wieczorowe/eva-lola/|/Sukienki-wieczorowe/ivon/|/Sukienki-wieczorowe/numoco/|/Sukienki-wizytowe/awama/|/Sukienki-wizytowe/dursi/|/Sukienki-wizytowe/figl/|/Sukienki-wizytowe/fobya/|/Sukienki-wizytowe/imesia/|
/Sukienki-wizytowe/infinite-you/|/Sukienki-wizytowe/ivon/|/Sukienki-wizytowe/katrus/|/Sukienki-wizytowe/lanti/|/Sukienki-wizytowe/lemoniade/|/Sukienki-wizytowe/makadamia/|/Sukienki-wizytowe/makeover/|/Sukienki-wizytowe/merribel/|
/Sukienki-wizytowe/moe/|/Sukienki-wizytowe/nife/|/Sukienki-wizytowe/nommo/|/Sukienki-wizytowe/numoco/|/Sukienki-wizytowe/tessita/|/Sukienki-z-cekinami/awama/|/Szlafroki-meskie/de-lafense/|/T-shirty-meskie/koszulk/|
/Teczki-meskie/paolo-peruzzi/|/Torby-meskie-na-ramie/solier/|/Torby-skorzane-meskie/always-wild/|/Torby-skorzane-meskie/br-drene/|/Torby-skorzane-meskie/paolo-peruzzi/|/Torby-skorzane-meskie/solier/|/Wisiorki/mona/|/Wisiorki/polly-design/|
/Wisiorki/staviori-wlochy/|/Wisiorki/wec-twoj-jubiler/|/Zawieszki/energetix-niemcy/|/Zawieszki/sentiell/|/Biustonosze-koronkowe/ava/|/Biustonosze-koronkowe/gaia/|
/Biustonosze-koronkowe/gorsenia/|/Biustonosze-koronkowe/gorteks/|/Biustonosze-koronkowe/kinga/|/Biustonosze-koronkowe/lupo-line/|/Biustonosze-koronkowe/mat/|/Biustonosze-koronkowe/nipplex/|
/Biustonosze-miekkie/gaia/|/Biustonosze-miekkie/gorsenia/|/Biustonosze-push-up/kinga/|/Biustonosze-usztywniane/ava/|/Biustonosze-usztywniane/gaia/|
/Biustonosze-usztywniane/kinga/|/Bokserki-meskie/atlantic/|/Bokserki-meskie/cornette/|/Bokserki-meskie/henderson/|/Bokserki-meskie/key/|/Bokserki-meskie/lama/|/Bokserki-meskie/pierre-cardin/|/Bokserki-meskie/rossli/|
/Bokserki-meskie/sesto-senso/|/Bokserki-meskie/umbro/|/Bransoletki-swarovski/myness/|/Bransoletki-sznurkowe/sentiell/|/Figi-damskie/atlantic/|/Figi-damskie/ava/|/Figi-damskie/babell/|/Figi-damskie/donella/|
/Figi-damskie/eldar/|/Figi-damskie/emili/|/Figi-damskie/ewana/|/Figi-damskie/gabidar/|/Figi-damskie/gaia/|/Figi-damskie/gorsenia/|/Figi-damskie/julimex/|/Figi-damskie/key/|/Figi-damskie/kinga/|/Figi-damskie/lama/|/Figi-damskie/lupo-line/|
/Figi-damskie/mat/|/Figi-damskie/mitex/|/Figi-damskie/modo/|/Figi-damskie/nipplex/|/Figi-damskie/wol-bar/|/Figi-damskie/wolbar/|/Koszulki-nocne/anais/|/Koszulki-nocne/aruelle/|/Koszulki-nocne/babell/|/Koszulki-nocne/babella/|
/Koszulki-nocne/betina/|/Koszulki-nocne/cana/|/Koszulki-nocne/cornette/|/Koszulki-nocne/de-lafense/|/Koszulki-nocne/dkaren/|/Koszulki-nocne/donna/|/Koszulki-nocne/eldar/|/Koszulki-nocne/gorsenia/|
/Koszulki-nocne/henderson-ladies/|/Koszulki-nocne/irall/|/Koszulki-nocne/italian-fashion/|/Koszulki-nocne/key/|/Koszulki-nocne/leinle/|/Koszulki-nocne/livco-corsetti/|/Koszulki-nocne/luna/|/Koszulki-nocne/lupo-line/|/Koszulki-nocne/nipplex/|
/Koszulki-nocne/regina/|/Koszulki-nocne/sensis/|/Koszulki-nocne/taro/|/Pizamy-damskie/aruelle/|/Pizamy-damskie/babella/|/Pizamy-damskie/cana/|/Pizamy-damskie/cornette/|/Pizamy-damskie/de-lafense/|/Pizamy-damskie/donna/|
/Pizamy-damskie/henderson-ladies/|/Pizamy-damskie/irall/|/Pizamy-damskie/italian-fashion/|/Pizamy-damskie/key/|/Pizamy-damskie/leinle/|/Pizamy-damskie/luna/|/Pizamy-damskie/regina/|/Pizamy-damskie/rossli/|/Pizamy-damskie/sensis/|
/Pizamy-damskie/taro/|/Slipy-meskie/atlantic/|/Slipy-meskie/cornette/|/Slipy-meskie/henderson/|/Slipy-meskie/key/|/Slipy-meskie/sesto-senso/|/Stringi-damskie/ava/|/Stringi-damskie/gabidar/|/Stringi-damskie/kinga/|/Stringi-damskie/nipplex/|
/Stringi-damskie/wol-bar/|/Stroje-kapielowe-dwuczesciowe/marko/|/Stroje-kapielowe-dwuczesciowe/self/|/Stroje-kapielowe-jednoczesciowe/marko/|/Stroje-kapielowe-jednoczesciowe/shepa/|/Szlafroki-damskie/aruelle/|/Szlafroki-damskie/de-lafense/|
/Szlafroki-damskie/dkaren/|/Szlafroki-damskie/irall/|/Szlafroki-damskie/l-l/|/Akcesoria-meskie/wyprzedaze/|/Bielizna-damska/wyprzedaze/|/Bielizna-meska/wyprzedaze/|/Spodnice/wyprzedaze/|/Sukienki/wyprzedaze/|
/Bielizna-nocna/wyprzedaze/|/Biustonosze/wyprzedaze/|/Majtki-damskie/wyprzedaze/|/Majtki-meskie/wyprzedaze/|/Okulary-meskie/wyprzedaze/|/Skarpetki-damskie/wyprzedaze/|/Sukienki-midi/wyprzedaze/|/Sukienki-olowkowe/wyprzedaze/|
/Sukienki-rozkloszowane/wyprzedaze/|/Sukienki-wizytowe/wyprzedaze/|/Figi-damskie/wyprzedaze/|/Akcesoria-damskie/welniane/|/Akcesoria-damskie/z-poliamidu/|/Akcesoria-damskie/skorzane/|/Akcesoria-damskie/lniane/|/Bielizna-damska/dzianinowe/|
/Bielizna-damska/z-poliestru/|/Bielizna-damska/welniane/|/Bielizna-damska/bawelniane/|/Bielizna-damska/z-elastanu/|/Bielizna-damska/z-wiskozy/|/Bielizna-damska/lniane/|/Bluzki-damskie/z-poliestru/|/Bluzki-damskie/welniane/|
/Bluzki-damskie/bawelniane/|/Bluzki-damskie/z-elastanu/|/Bluzki-damskie/z-wiskozy/|/Bluzki-damskie/lniane/|/Spodnice/dzianinowe/|/Spodnice/z-poliestru/|/Spodnice/welniane/|/Spodnice/bawelniane/|/Spodnice/z-elastanu/|/Spodnice/z-wiskozy/|
/Spodnice/lniane/|/Sukienki/dzianinowe/|/Sukienki/z-poliestru/|/Sukienki/welniane/|/Sukienki/bawelniane/|/Sukienki/z-poliamidu/|/Sukienki/z-elastanu/|/Sukienki/z-wiskozy/|/Sukienki/z-nylonu/|/Sukienki/z-tkaniny/|/Sukienki/z-szyfonu/|
/Sukienki/lniane/|/Torby-meskie/ze-skory-ekologicznej/|/Torebki-damskie/skorzane/|/Torebki-damskie/ze-skory-ekologicznej/|/Bielizna-nocna/dzianinowe/|/Bielizna-nocna/z-poliestru/|/Bielizna-nocna/welniane/|/Bielizna-nocna/bawelniane/|
/Bielizna-nocna/z-elastanu/|/Bielizna-nocna/z-wiskozy/|/Bielizna-nocna/lniane/|/Bluzki-oversize/z-elastanu/|/Bluzki-oversize/z-wiskozy/|/Czapki-damskie/welniane/|/Czapki-damskie/z-poliamidu/|/Czapki-damskie/lniane/|/Kopertowki/skorzane/|
/Kopertowki/ze-skory-ekologicznej/|/Paski-damskie/skorzane/|/Plecaki-damskie/skorzane/|/Spodnice-midi/z-poliestru/|/Spodnice-midi/z-elastanu/|/Spodnice-midi/z-wiskozy/|/Spodnice-mini/z-poliestru/|/Spodnice-mini/welniane/|
/Spodnice-mini/z-elastanu/|/Spodnice-mini/lniane/|/Spodnice-olowkowe/dzianinowe/|/Spodnice-olowkowe/z-poliestru/|/Spodnice-olowkowe/welniane/|/Spodnice-olowkowe/bawelniane/|/Spodnice-olowkowe/z-elastanu/|/Spodnice-olowkowe/z-wiskozy/|
/Spodnice-olowkowe/lniane/|/Spodnice-rozkloszowane/z-poliestru/|/Spodnice-rozkloszowane/z-elastanu/|/Spodnice-rozkloszowane/z-wiskozy/|/Spodnice-trapezowe/z-poliestru/|/Spodnice-trapezowe/z-wiskozy/|/Sukienki-asymetryczne/dzianinowe/|
/Sukienki-asymetryczne/z-poliestru/|/Sukienki-asymetryczne/welniane/|/Sukienki-asymetryczne/bawelniane/|/Sukienki-asymetryczne/z-elastanu/|/Sukienki-asymetryczne/z-wiskozy/|/Sukienki-asymetryczne/lniane/|/Sukienki-do-pracy/dzianinowe/|
/Sukienki-do-pracy/z-poliestru/|/Sukienki-do-pracy/welniane/|/Sukienki-do-pracy/bawelniane/|/Sukienki-do-pracy/z-elastanu/|/Sukienki-do-pracy/z-wiskozy/|/Sukienki-do-pracy/lniane/|/Sukienki-dresowe/dzianinowe/|/Sukienki-dresowe/z-poliestru/|
/Sukienki-dresowe/welniane/|/Sukienki-dresowe/bawelniane/|/Sukienki-dresowe/z-elastanu/|/Sukienki-dresowe/z-wiskozy/|/Sukienki-dresowe/lniane/|/Sukienki-dzinsowe/z-poliestru/|/Sukienki-dzinsowe/z-elastanu/|/Sukienki-dzinsowe/z-wiskozy/|
/Sukienki-gorsetowe/z-poliestru/|/Sukienki-koktajlowe/z-poliestru/|/Sukienki-koktajlowe/z-elastanu/|/Sukienki-koktajlowe/z-wiskozy/|/Sukienki-koktajlowe/lniane/|/Sukienki-koronkowe/z-poliestru/|/Sukienki-koronkowe/z-elastanu/|
/Sukienki-koronkowe/z-wiskozy/|/Sukienki-koszulowe/z-poliestru/|/Sukienki-koszulowe/z-elastanu/|/Sukienki-koszulowe/z-wiskozy/|/Sukienki-maxi/dzianinowe/|/Sukienki-maxi/z-poliestru/|/Sukienki-maxi/welniane/|/Sukienki-maxi/bawelniane/|
/Sukienki-maxi/z-elastanu/|/Sukienki-maxi/z-wiskozy/|/Sukienki-maxi/lniane/|/Sukienki-midi/dzianinowe/|/Sukienki-midi/z-poliestru/|/Sukienki-midi/welniane/|/Sukienki-midi/bawelniane/|/Sukienki-midi/z-elastanu/|/Sukienki-midi/z-wiskozy/|
/Sukienki-midi/lniane/|/Sukienki-mini/z-poliestru/|/Sukienki-mini/welniane/|/Sukienki-mini/bawelniane/|/Sukienki-mini/z-elastanu/|/Sukienki-mini/z-wiskozy/|/Sukienki-mini/lniane/|/Sukienki-na-wesele/z-poliestru/|/Sukienki-na-wesele/z-elastanu/|
/Sukienki-na-wesele/z-wiskozy/|/Sukienki-olowkowe/z-poliestru/|/Sukienki-olowkowe/welniane/|/Sukienki-olowkowe/bawelniane/|/Sukienki-olowkowe/z-elastanu/|/Sukienki-olowkowe/z-wiskozy/|/Sukienki-olowkowe/lniane/|/Sukienki-pastelowe/z-poliestru/|
/Sukienki-plus-size/z-poliestru/|/Sukienki-plus-size/z-wiskozy/|/Sukienki-rozkloszowane/dzianinowe/|/Sukienki-rozkloszowane/z-poliestru/|/Sukienki-rozkloszowane/welniane/|/Sukienki-rozkloszowane/bawelniane/|/Sukienki-rozkloszowane/z-elastanu/|
/Sukienki-rozkloszowane/z-wiskozy/|/Sukienki-rozkloszowane/lniane/|/Sukienki-sportowe/z-poliestru/|/Sukienki-sportowe/welniane/|/Sukienki-sportowe/bawelniane/|/Sukienki-sportowe/z-elastanu/|/Sukienki-sportowe/z-wiskozy/|/Sukienki-sportowe/lniane/|
/Sukienki-trapezowe/dzianinowe/|/Sukienki-trapezowe/z-poliestru/|/Sukienki-trapezowe/welniane/|/Sukienki-trapezowe/bawelniane/|/Sukienki-trapezowe/z-elastanu/|/Sukienki-trapezowe/z-wiskozy/|/Sukienki-trapezowe/lniane/|/Sukienki-wieczorowe/z-poliestru/|
/Sukienki-wieczorowe/z-elastanu/|/Sukienki-wieczorowe/z-wiskozy/|/Sukienki-wizytowe/dzianinowe/|/Sukienki-wizytowe/z-poliestru/|/Sukienki-wizytowe/welniane/|/Sukienki-wizytowe/bawelniane/|/Sukienki-wizytowe/z-poliamidu/|/Sukienki-wizytowe/z-elastanu/|
/Sukienki-wizytowe/z-wiskozy/|/Sukienki-wizytowe/z-nylonu/|/Sukienki-wizytowe/z-szyfonu/|/Sukienki-wizytowe/lniane/|/Sukienki-z-cekinami/z-poliestru/|/Sukienki-z-cekinami/z-elastanu/|/Sukienki-za-kolano/z-poliestru/|/Pizamy-damskie/dzianinowe/|
/Pizamy-damskie/z-poliestru/|/Pizamy-damskie/welniane/|/Pizamy-damskie/bawelniane/|/Pizamy-damskie/z-elastanu/|/Pizamy-damskie/z-wiskozy/|/Pizamy-damskie/lniane/|/Sukienki/na-wesele/|/Sukienki/wieczorowe/|/Sukienki/na-studniowke/|
/Sukienki-asymetryczne/wieczorowe/|/Sukienki-do-pracy/na-wesele/|/Sukienki-koktajlowe/na-wesele/|/Sukienki-koktajlowe/wieczorowe/|/Sukienki-koronkowe/na-wesele/|/Sukienki-koronkowe/wieczorowe/|/Sukienki-koronkowe/na-studniowke/|
/Sukienki-maxi/wieczorowe/|/Sukienki-mini/na-wesele/|/Sukienki-mini/wieczorowe/|/Sukienki-na-wesele/na-wesele/|/Sukienki-olowkowe/na-wesele/|/Sukienki-olowkowe/wieczorowe/|/Sukienki-pastelowe/na-wesele/|/Sukienki-rozkloszowane/na-wesele/|
/Sukienki-rozkloszowane/wieczorowe/|/Sukienki-trapezowe/na-wesele/|/Sukienki-wieczorowe/na-wesele/|/Sukienki-wieczorowe/wieczorowe/|/Sukienki-wieczorowe/na-studniowke/|/Sukienki-wizytowe/na-wesele/|/Sukienki-wizytowe/wieczorowe/|
/Sukienki-wizytowe/na-studniowke/|/Sukienki-z-cekinami/na-wesele/|/Sukienki-z-cekinami/wieczorowe/|/Sukienki/na-lato/|/Sukienki-do-pracy/na-lato/|/Sukienki-midi/na-lato/|/Sukienki-rozkloszowane/na-lato/|/Sukienki-wizytowe/na-lato/|
/Spodnice/casualowe/|/Spodnice/eleganckie/|/Spodnice/klasyczne/|/Sukienki/casualowe/|/Sukienki/eleganckie/|/Sukienki/boho/|/Sukienki/klasyczne/|/Sukienki/mlodziezowe/|/Spodnice-olowkowe/eleganckie/|/Spodnice-olowkowe/klasyczne/|
/Sukienki-asymetryczne/eleganckie/|/Sukienki-do-pracy/eleganckie/|/Sukienki-do-pracy/klasyczne/|/Sukienki-do-pracy/mlodziezowe/|/Sukienki-koronkowe/mlodziezowe/|/Sukienki-midi/eleganckie/|/Sukienki-midi/klasyczne/|/Sukienki-mini/mlodziezowe/|
/Sukienki-na-wesele/eleganckie/|/Sukienki-olowkowe/eleganckie/|/Sukienki-olowkowe/klasyczne/|/Sukienki-olowkowe/mlodziezowe/|/Sukienki-rozkloszowane/eleganckie/|/Sukienki-rozkloszowane/klasyczne/|/Sukienki-rozkloszowane/mlodziezowe/|
/Sukienki-trapezowe/mlodziezowe/|/Sukienki-wieczorowe/eleganckie/|/Sukienki-wieczorowe/mlodziezowe/|/Sukienki-wizytowe/casualowe/|/Sukienki-wizytowe/eleganckie/|/Sukienki-wizytowe/boho/|/Sukienki-wizytowe/klasyczne/|
/Sukienki-wizytowe/mlodziezowe/|/Bielizna-damska/z-nadrukiem/|/Bielizna-damska/w-kwiaty/|/Bluzki-damskie/w-kwiaty/|/Spodnice/w-kwiaty/|/Sukienki/z-nadrukiem/|/Sukienki/z-aplikacja/|/Sukienki/w-kwiaty/|/Spodnice-rozkloszowane/w-kwiaty/|
/Stroje-kapielowe-damskie/z-nadrukiem/|/Stroje-kapielowe-damskie/w-kwiaty/|/Sukienki-asymetryczne/w-kwiaty/|/Sukienki-do-pracy/z-nadrukiem/|/Sukienki-do-pracy/w-kwiaty/|/Sukienki-maxi/w-kwiaty/|/Sukienki-midi/w-kwiaty/|/Sukienki-mini/w-kwiaty/|
/Sukienki-olowkowe/w-kwiaty/|/Sukienki-rozkloszowane/w-kwiaty/|/Sukienki-wizytowe/w-kwiaty/|/Tankini/z-nadrukiem/|/Stroje-kapielowe-damskie/aquarilla/|/Sukienki-koronkowe/zlote/|/Sukienki-koronkowe/biale/|/Sukienki/teresa-kopias/|
/Sukienki-na-wesele/czerwone/|/Sukienki-na-wesele/krotkie/|/Trampki-damskie/biale/|/Sukienki-na-wesele/dlugie/|/Sukienki-na-wesele/srebrne/|/Sukienki-midi/na-wesele/|/Sukienki-wieczorowe/srebrne/|/Buty-damskie/helios/|/Buty-damskie/jezzi/|
/Naszyjniki/kuznia-nehesi/|/Sukienki-koronkowe/czerwone/|/Stroje-kapielowe-dwuczesciowe/krisline/|/Sukienki-na-wesele/zielone/|/Trampki-damskie/big-star/|/Botki-damskie/juma/|/Buty-damskie/excel/|/Buty-meskie/morek/|/Sukienki-wieczorowe/biale/|
/Sukienki-na-wesele/niebieskie/|/Sukienki-na-wesele/w-kwiaty/|/Sukienki-plus-size/z-haftem/|/Sukienki-trapezowe/zielone/|/Sukienki-wieczorowe/zlote/|/Buty-damskie/szare/|/Sukienki-na-wesele/blekitne/|/Sukienki-na-wesele/fioletowe/|
/Sukienki-na-wesele/wieczorowe/|/Sukienki-na-wesele/wyprzedaze/|/Botki-damskie/bezowe/|/Buty-damskie/rieker/|/Sukienki-na-wesele/rozowe/|/Sukienki-na-wesele/turkusowe/|/Sukienki-trapezowe/wyprzedaze/|/Sukienki-wieczorowe/styl-i-ja/|
/Trampki-damskie/czerwone/|/Buty-damskie/czerwone/|/Buty-dzieciece/big-star/|/Czolenka-damskie/tymoteo/|/Klapki-damskie/zlote/|/Koszule-meskie/profuomo/|/Plecaki-damskie/bamba-concept/|/Plecaki-damskie/eleganckie/|/Sukienki-dzinsowe/lanti/|
/Sukienki-plus-size/w-kwiaty/|/Sukienki-trapezowe/w-kwiaty/|/Biustonosze/wiesmann/|/Bluzki-damskie/bezowe/|/Buty-damskie/biale/|/Buty-damskie/na-rzepy/|/Buty-damskie/zlote/|/Gorsety-damskie/chilirose/|/Kolczyki/joanna-muzyka-studio/|
/Sukienki-asymetryczne/na-wesele/|/Sukienki-dresowe/dlugie/|/Sukienki-dzinsowe/dlugie/|/Sukienki-koronkowe/lejdi/|/Sukienki-koronkowe/z-dlugim-rekawem/|/Sukienki-na-wesele/klasyczne/|/Sukienki-na-wesele/szare/|/Sukienki-na-wesele/z-jedwabiu/|
/Sukienki-na-wesele/zlote/|/Sukienki-plus-size/biale/|/Sukienki-wieczorowe/krotkie/|/Szlafroki-damskie/akcent/|/Bizuteria-damska/flurry/|/Body-damskie/czerwone/|/Botki-damskie/niebieskie/|/Buty-damskie/bezowe/|/Buty-damskie/big-star/|
/Buty-damskie/evento/|/Buty-damskie/juma/|/Buty-meskie/na-lato/|/Buty-sportowe-damskie/biale/|/Czolenka-damskie/bravo-moda/|/Klapki-damskie/kampa/|/Kolczyki/boske/|/Rybaczki-damskie/4f/|/Stroje-kapielowe-dwuczesciowe/w-paski/|
/Sukienki-koktajlowe/czerwone/|/Sukienki-na-wesele/bezowe/|/Sukienki-na-wesele/z-haftem/|/Sukienki-plus-size/wieczorowe/|/Sukienki-sportowe/eleganckie/|/Sukienki-wieczorowe/szare/|/Sukienki/zlote/|/Baleriny-damskie/lu-boo/|
/Bielizna-damska/heartbreaks-and-promises-lingerie/|/Bizuteria-damska/lahovska/|/Buty-damskie/brazowe/|/Buty-damskie/import/|/Buty-damskie/zaxy/|/Buty-dzieciece/biale/|/Buty-dzieciece/mido-noster/|/Buty-meskie/the-north-face/|
/Czolenka-damskie/acord/|/Dresy-damskie/bawelniane/|/Koszule-meskie-sportowe/profuomo/|/Krawaty/hemley/|/Okulary-meskie/polarzone/|/Spodnie-damskie/z-jerseyu/|/Stroje-kapielowe-damskie/primo/|/Stroje-kapielowe-jednoczesciowe/sapphire/|
/Sukienki-dziewczece/biale/|/Sukienki-koktajlowe/biale/|/Sukienki-koronkowe/granatowe/|/Sukienki-maxi/na-lato/|/Sukienki-na-wesele/na-lato/|/Sukienki-plus-size/na-wesele/|/Sukienki-plus-size/szare/|/Sukienki-z-cekinami/bezowe/|
/Sukienki/myoko-natural-direction/|/Trampki-damskie/czarne/|/Zegarki-damskie/biale/|';

$noindexList = explode('|', $noindexValues);

foreach ($noindexList as $value) {
	$newValue = trim($value);
	$sql = "INSERT INTO `jos_without_noindex` (`path`)"
	."VALUES ('$newValue')"
	;
	$result = mysql_query($sql);
}*/

// b
/*$noindexValues = '/Sukienki-koronkowe/zlote/|/Sukienki-dzinsowe/numoco/|/Naszyjniki/kuznia-nehesi/|/Bizuteria-damska/boske/|/Buty-damskie/excel/|/Buty-meskie/morek/|/Stroje-kapielowe-dwuczesciowe/krisline/|
/Sukienki-plus-size/z-haftem/|/Sukienki-wieczorowe/styl-i-ja/|/Bizuteria-damska/turkusowe/|/Sukienki-trapezowe/wyprzedaze/|/Bizuteria-damska/czerwone/|/Kolczyki/modelinova/|
/Koszule-meskie/profuomo/|/Czolenka-damskie/tymoteo/|/Kolczyki/joanna-muzyka-studio/|/Plecaki-damskie/bamba-concept/|/Sukienki-dzinsowe/lanti/|/Czolenka-damskie/bravo-moda/|
/Gorsety-damskie/chilirose/|/Klapki-damskie/kampa/|/Stroje-kapielowe-jednoczesciowe/sapphire/|/Sukienki-koronkowe/lejdi/|/Szlafroki-damskie/akcent/|
/Bizuteria-damska/flurry/|/Buty-damskie/evento/|/Kolczyki/boske/|/Okulary-meskie/polarzone/|/Bielizna-damska/heartbreaks-and-promises-lingerie/|/Bizuteria-damska/lahovska/|
/Bizuteria-damska/rozowe/|/Buty-damskie/import/|/Koszule-meskie-sportowe/profuomo/|/Krawaty/hemley/|/Sukienki-plus-size/szare/|/Sukienki-z-cekinami/bezowe/|
/Sukienki/myoko-natural-direction/|/Bielizna-damska/zolte/|/Bielizna-meska/wyprzedaze/|/Bizuteria-damska/zielone/|/Sukienki-dzinsowe/niebieskie/|/Sukienki-olowkowe/rozowe/|
/Akcesoria-meskie/samsonite/|/Bielizna-damska/blekitne/|/Bielizna-damska/mietowe/|/Okulary-meskie/lozano/|/Stroje-kapielowe-jednoczesciowe/shepa/|/Sukienki-koktajlowe/z-wiskozy/|
/Sukienki-maxi/welniane/|/Sukienki-midi/makadamia/|/Sukienki-olowkowe/ivon/|/Sukienki-trapezowe/szare/|/Akcesoria-damskie/valentini/|/Bielizna-damska/cana/|
/Bizuteria-damska/magneska/|/Bizuteria-damska/modelinova/|/Bizuteria-damska/mona/|/Bizuteria-damska/niebieskie/|/Bizuteria-damska/szare/|/Bransoletki/energetix-niemcy/|
/Koszulki-nocne/granatowe/|/Koszulki-nocne/szare/|/Rajstopy-damskie/knittex/|/Spodnice/wyprzedaze/|/Sukienki-asymetryczne/bawelniane/|/Sukienki-asymetryczne/rozowe/|/Sukienki-do-pracy/dlugie/|
/Sukienki-do-pracy/z-wiskozy/|/Sukienki-dresowe/moe/|/Sukienki-koronkowe/z-wiskozy/|/Sukienki-koszulowe/z-wiskozy/|/Sukienki-midi/nife/|/Sukienki-midi/nommo/|/Sukienki-mini/awama/|
/Sukienki-mini/krotkie/|/Sukienki-olowkowe/granatowe/|/Sukienki-olowkowe/szare/|/Sukienki-olowkowe/z-poliestru/|/Sukienki-plus-size/z-wiskozy/|/Sukienki-sportowe/szare/|
/Sukienki-trapezowe/makadamia/|/Sukienki-z-cekinami/awama/|/Sukienki/dlugie/|/Sukienki/srednie/ 0-10|/Sukienki/krotkie/|/Sukienki-asymetryczne/srednie/ 0-10|/Sukienki-do-pracy/dlugie/ 0-10|/Sukienki-do-pracy/srednie/ 0-10|/Sukienki-dresowe/srednie/ 0-10|/Sukienki-maxi/dlugie/|/Sukienki-midi/srednie/ 0-10|/Sukienki-mini/krotkie/| 0-10
/Sukienki-olowkowe/srednie/ 0-10|/Sukienki-olowkowe/krotkie/ 0-10|/Sukienki-rozkloszowane/srednie/ 0-10|/Sukienki-rozkloszowane/krotkie/|/Sukienki-trapezowe/krotkie/ 0-10|/Sukienki-wieczorowe/dlugie/|/Sukienki-wizytowe/dlugie/|/Sukienki-wizytowe/srednie/| 0-10
/Sukienki-wizytowe/krotkie/|/Sukienki/z-dlugim-rekawem/|/Sukienki/z-krotkim-rekawem/|/Sukienki/bez-rekawa/ 0-10|/Sukienki-do-pracy/z-krotkim-rekawem/ 0-10|/Sukienki-midi/bez-rekawa/ 0-10|/Sukienki-olowkowe/bez-rekawa/ 0-10|/Sukienki-rozkloszowane/z-krotkim-rekawem/|
/Sukienki-rozkloszowane/bez-rekawa/ 0-10|/Sukienki-wizytowe/z-dlugim-rekawem/|/Sukienki-wizytowe/z-krotkim-rekawem/|/Sukienki-wizytowe/bez-rekawa/ 0-10|/Akcesoria-damskie/czarne/ 0-10|/Akcesoria-damskie/czerwone/ 0-10|/Akcesoria-damskie/brazowe/| 0-10
/Akcesoria-damskie/niebieskie/ 0-10|/Akcesoria-damskie/rozowe/ 0-10|/Akcesoria-damskie/zielone/ 0-10|/Akcesoria-meskie/czarne/ 0-10|/Akcesoria-meskie/czerwone/ 0-10|/Akcesoria-meskie/granatowe/ 0-10|/Akcesoria-meskie/brazowe/ 0-10|/Akcesoria-meskie/szare/| 0-10
/Bielizna-damska/biale/|/Bielizna-damska/czarne/|/Bielizna-damska/czerwone/|/Bielizna-damska/granatowe/|/Bielizna-damska/bezowe/ 0-10|/Bielizna-damska/bordowe/|/Bielizna-damska/blekitne/ 0-10|/Bielizna-damska/mietowe/ 0-10|/Bielizna-damska/niebieskie/|
/Bielizna-damska/rozowe/|/Bielizna-damska/szare/ 0-10|/Bielizna-damska/turkusowe/|/Bielizna-damska/zielone/|/Bielizna-damska/zolte/ 0-10|/Bielizna-meska/biale/ 0-10|/Bielizna-meska/czarne/ 0-10|/Bielizna-meska/czerwone/ 0-10|/Bielizna-meska/granatowe/| 0-10
/Bielizna-meska/niebieskie/ 0-10|/Bielizna-meska/szare/ 0-10|/Bizuteria-damska/biale/ 0-10|/Bizuteria-damska/czarne/|/Bizuteria-damska/czerwone/ 0-10|/Bizuteria-damska/bezowe/ 0-10|/Bizuteria-damska/brazowe/ 0-10|/Bizuteria-damska/fioletowe/ 0-10|/Bizuteria-damska/niebieskie/ 0-10|
/Bizuteria-damska/rozowe/ 0-10|/Bizuteria-damska/srebrne/|/Bizuteria-damska/szare/ 0-10|/Bizuteria-damska/turkusowe/ 0-10|/Bizuteria-damska/wielokolorowe/ 0-10|/Bizuteria-damska/zielone/ 0-10|/Bizuteria-damska/zolte/ 0-10|/Bizuteria-damska/zlote/|/Bluzki-damskie/biale/|
/Bluzki-damskie/czarne/|/Buty-damskie/czarne/|/Koszulki-meskie/biale/|/Koszulki-meskie/czarne/|/Koszulki-meskie/czerwone/|/Koszulki-meskie/granatowe/ 0-10|/Plaszcze-damskie/czarne/|/Spodnice/czarne/|/Spodnice/czerwone/|/Spodnice/granatowe/|
/Spodnice/bezowe/|/Spodnice/rozowe/|/Spodnice/szare/|/Spodnie-damskie/czarne/|/Spodnie-damskie/niebieskie/|/Sukienki/biale/|/Sukienki/czarne/|/Sukienki/czerwone/|/Sukienki/granatowe/|/Sukienki/bezowe/|/Sukienki/bordowe/|/Sukienki/brazowe/|
/Sukienki/blekitne/|/Sukienki/mietowe/|/Sukienki/niebieskie/|/Sukienki/rozowe/|/Sukienki/szare/|/Sukienki/zielone/|/Sukienki/zolte/|/Torby-meskie/czarne/ 0-10|/Torby-meskie/brazowe/|/Torebki-damskie/czarne/|/Torebki-damskie/szare/|
/Zegarki-damskie/czarne/|/Zegarki-meskie/czarne/|/Bielizna-nocna/biale/|/Bielizna-nocna/czarne/|/Bielizna-nocna/czerwone/|/Bielizna-nocna/granatowe/ 0-10|/Bielizna-nocna/bordowe/ 0-10|/Bielizna-nocna/rozowe/ 0-10|/Bielizna-nocna/szare/ 0-10|/Biustonosze/biale/|
/Biustonosze/czarne/|/Biustonosze/czerwone/|/Biustonosze/bezowe/ 0-10|/Biustonosze/niebieskie/ 0-10|/Biustonosze/rozowe/ 0-10|/Biustonosze/szare/ 0-10|/Body-damskie/czarne/|/Bojowki-damskie/niebieskie/ 0-10|/Bransoletki/biale/|/Bransoletki/czarne/|
/Bransoletki/czerwone/|/Bransoletki/rozowe/|/Bransoletki/srebrne/|/Bransoletki/zielone/|/Bransoletki/zolte/|/Bransoletki/zlote/|/Kapielowki/czarne/|/Kolczyki/biale/|/Kolczyki/czarne/|/Kolczyki/czerwone/|/Kolczyki/rozowe/|/Kolczyki/srebrne/|
/Kolczyki/zolte/|/Kolczyki/zlote/|/Lancuszki/srebrne/|/Lancuszki/zolte/ 0-10|/Majtki-damskie/biale/|/Majtki-damskie/czarne/|/Majtki-damskie/czerwone/|/Majtki-damskie/bezowe/ 0-10|/Majtki-meskie/biale/|/Majtki-meskie/czarne/ 0-10|/Majtki-meskie/czerwone/ 0-10|
/Majtki-meskie/granatowe/ 0-10|/Majtki-meskie/niebieskie/ 0-10|/Majtki-meskie/szare/ 0-10|/Naszyjniki/biale/ 0-10|/Naszyjniki/czarne/|/Naszyjniki/rozowe/ 0-10|/Naszyjniki/srebrne/|/Naszyjniki/zolte/ 0-10|/Naszyjniki/zlote/|/Okulary-damskie/czarne/|/Okulary-meskie/czarne/|
/Pierscionki/biale/ 0-10|/Pierscionki/czarne/|/Pierscionki/rozowe/ 0-10|/Pierscionki/srebrne/|/Pierscionki/zolte/ 0-10|/Plecaki-damskie/czarne/|/Portfele-damskie/czarne/|/Portfele-damskie/czerwone/|/Portfele-damskie/brazowe/ 0-10|/Portfele-damskie/niebieskie/|
/Portfele-damskie/rozowe/|/Portfele-damskie/zielone/|/Portfele-meskie/czarne/ 0-10|/Portfele-meskie/czerwone/ 0-10|/Portfele-meskie/granatowe/ 0-10|/Portfele-meskie/brazowe/ 0-10|/Spodnice-olowkowe/czarne/|/Spodnice-olowkowe/szare/ 0-10|/Spodnice-rozkloszowane/czarne/|
/Stroje-kapielowe-damskie/biale/|/Stroje-kapielowe-damskie/czarne/|/Stroje-kapielowe-damskie/niebieskie/|/Stroje-kapielowe-damskie/rozowe/|/Sukienki-asymetryczne/czarne/|/Sukienki-asymetryczne/czerwone/|/Sukienki-asymetryczne/granatowe/ 0-10|
/Sukienki-asymetryczne/rozowe/ 0-10|/Sukienki-asymetryczne/szare/ 0-10|/Sukienki-do-pracy/biale/ 0-10|/Sukienki-do-pracy/czarne/ 0-10|/Sukienki-do-pracy/czerwone/ 0-10|/Sukienki-do-pracy/niebieskie/ 0-10|/Sukienki-do-pracy/rozowe/ 0-10|/Sukienki-do-pracy/zielone/ 0-10|
/Sukienki-dresowe/czarne/|/Sukienki-dresowe/szare/|/Sukienki-dzinsowe/niebieskie/ 0-10|/Sukienki-koktajlowe/czarne/|/Sukienki-koronkowe/czarne/|/Sukienki-koronkowe/rozowe/|/Sukienki-koszulowe/czarne/|/Sukienki-maxi/czarne/|/Sukienki-midi/czarne/|
/Sukienki-midi/czerwone/|/Sukienki-midi/granatowe/|/Sukienki-midi/bezowe/ 0-10|/Sukienki-midi/niebieskie/|/Sukienki-midi/rozowe/ 0-10|/Sukienki-midi/szare/ 0-10|/Sukienki-midi/zielone/|/Sukienki-mini/czarne/|/Sukienki-mini/czerwone/|/Sukienki-mini/granatowe/ 0-10|
/Sukienki-mini/bezowe/ 0-10|/Sukienki-mini/szare/ 0-10|/Sukienki-olowkowe/czarne/|/Sukienki-olowkowe/czerwone/|/Sukienki-olowkowe/granatowe/ 0-10|/Sukienki-olowkowe/rozowe/ 0-10|/Sukienki-olowkowe/szare/ 0-10|/Sukienki-olowkowe/zielone/|/Sukienki-rozkloszowane/biale/|
/Sukienki-rozkloszowane/czarne/|/Sukienki-rozkloszowane/czerwone/|/Sukienki-rozkloszowane/granatowe/|/Sukienki-rozkloszowane/bezowe/ 0-10|/Sukienki-rozkloszowane/bordowe/|/Sukienki-rozkloszowane/niebieskie/|/Sukienki-rozkloszowane/rozowe/|
/Sukienki-rozkloszowane/szare/|/Sukienki-rozkloszowane/zielone/|/Sukienki-sportowe/czarne/|/Sukienki-sportowe/szare/ 0-10|/Sukienki-trapezowe/czarne/|/Sukienki-trapezowe/czerwone/|/Sukienki-trapezowe/granatowe/ 0-10|/Sukienki-trapezowe/rozowe/ 0-10|
/Sukienki-trapezowe/szare/ 0-10|/Sukienki-wieczorowe/czarne/|/Sukienki-wieczorowe/czerwone/|/Sukienki-wieczorowe/granatowe/|/Sukienki-wieczorowe/bordowe/|/Sukienki-wieczorowe/rozowe/|/Sukienki-wizytowe/biale/|/Sukienki-wizytowe/czarne/|
/Sukienki-wizytowe/czerwone/|/Sukienki-wizytowe/granatowe/|/Sukienki-wizytowe/bezowe/ 0-10|/Sukienki-wizytowe/bordowe/ 0-10|/Sukienki-wizytowe/brazowe/ 0-10|/Sukienki-wizytowe/blekitne/ 0-10|/Sukienki-wizytowe/niebieskie/|/Sukienki-wizytowe/rozowe/ 0-10|
/Sukienki-wizytowe/szare/|/Sukienki-wizytowe/zielone/|/Sukienki-wizytowe/zolte/ 0-10|/Sukienki-z-cekinami/czarne/|/T-shirty-meskie/biale/|/T-shirty-meskie/czarne/|/T-shirty-meskie/czerwone/ 0-10|/T-shirty-meskie/granatowe/ 0-10|/Teczki-meskie/czarne/ 0-10|
/Torby-skorzane-meskie/czarne/ 0-10|/Torby-skorzane-meskie/brazowe/ 0-10|/Wisiorki/biale/ 0-10|/Wisiorki/srebrne/|/Wisiorki/zolte/ 0-10|/Zawieszki/biale/ 0-10|/Zawieszki/czarne/ 0-10|/Zawieszki/rozowe/ 0-10|/Zawieszki/srebrne/|/Zawieszki/zolte/ 0-10|/Bikini/biale/|/Bikini/czarne/|
/Bikini/niebieskie/|/Biustonosze-koronkowe/biale/ 0-10|/Biustonosze-koronkowe/czarne/ 0-10|/Biustonosze-koronkowe/bezowe/ 0-10|/Biustonosze-koronkowe/niebieskie/ 0-10|/Biustonosze-koronkowe/rozowe/ 0-10|/Biustonosze-minimizer/biale/ 0-10|/Biustonosze-minimizer/czarne/ 0-10|
/Biustonosze-usztywniane/biale/ 0-10|/Biustonosze-usztywniane/czarne/ 0-10|/Bokserki-meskie/czarne/|/Bokserki-meskie/granatowe/ 0-10|/Bokserki-meskie/szare/ 0-10|/Figi-damskie/biale/|/Figi-damskie/czarne/|/Figi-damskie/czerwone/|/Figi-damskie/bezowe/ 0-10|
/Koszulki-nocne/biale/|/Koszulki-nocne/czarne/|/Koszulki-nocne/czerwone/|/Koszulki-nocne/granatowe/ 0-10|/Koszulki-nocne/rozowe/|/Koszulki-nocne/szare/ 0-10|/Pizamy-damskie/granatowe/ 0-10|/Pizamy-damskie/rozowe/ 0-10|/Pizamy-damskie/szare/ 0-10|/Slipy-meskie/biale/|
/Slipy-meskie/czarne/|/Slipy-meskie/granatowe/ 0-10|/Stringi-damskie/biale/|/Szlafroki-damskie/czarne/|/Tankini/biale/ 0|/Tankini/czarne/ 0|/Akcesoria-damskie/4u-cavaldi/ 0|/Akcesoria-damskie/arctica/ 0-10|/Akcesoria-damskie/art 0-10/|/Akcesoria-damskie/e-zegarki/ 0-10|
/Akcesoria-damskie/kamea/ 0-10|/Akcesoria-damskie/lorenti/ 0-10|/Akcesoria-damskie/milano-design/ 0-10|/Akcesoria-damskie/montana/ 0-10|/Akcesoria-damskie/rovicky/ 0-10|/Akcesoria-damskie/valentini/ 0-10|/Akcesoria-meskie/always-wild/ 0-10|/Akcesoria-meskie/arctica/ 0-10|
/Akcesoria-meskie/br-drene/ 0-10|/Akcesoria-meskie/buffalo-wild/ 0-10|/Akcesoria-meskie/draco/ 0-10|/Akcesoria-meskie/e-zegarki 0-10/|/Akcesoria-meskie/lozano/ 0-10|/Akcesoria-meskie/montana/ 0-10|/Akcesoria-meskie/pierre-andreus/ 0-10|/Akcesoria-meskie/polarized/ 0-10|
/Akcesoria-meskie/rovicky/ 0-10|/Akcesoria-meskie/samsonite/ 0-10|/Akcesoria-meskie/solier/ 0-10|/Akcesoria-meskie/stylion/ 0-10|/Akcesoria-meskie/sunoptic/ 0-10|/Akcesoria-meskie/valentini/ 0-10|/Bielizna-damska/anais/|/Bielizna-damska/aruelle/ 0-10|/Bielizna-damska/atlantic/|
/Bielizna-damska/ava/|/Bielizna-damska/ava-lingerie/ 0-10|/Bielizna-damska/axami/|/Bielizna-damska/babell/ 0-10|/Bielizna-damska/babella/ 0-10|/Bielizna-damska/betina/ 0-10|/Bielizna-damska/cana/ 0-10|/Bielizna-damska/cornette/ 0-10|
/Bielizna-damska/de-lafense/ 0-10|/Bielizna-damska/dkaren/ 0-10|/Bielizna-damska/donella/ 0-10|/Bielizna-damska/donna/|/Bielizna-damska/eldar/|/Bielizna-damska/emili/ 0-10|/Bielizna-damska/eso-hen/ 0-10|/Bielizna-damska/esotiq/|/Bielizna-damska/esotiq-henderson/ 0-10|
/Bielizna-damska/ewana/|/Bielizna-damska/figl/ 0-10|/Bielizna-damska/fiore/ 0-10|/Bielizna-damska/gabidar/ 0-10|/Bielizna-damska/gabriella/ 0-10|/Bielizna-damska/gaia/|/Bielizna-damska/gatta/|/Bielizna-damska/gorsenia/|/Bielizna-damska/gorteks/|
/Bielizna-damska/henderson-ladies/ 0-10|/Bielizna-damska/irall/|/Bielizna-damska/italian-fashion/|/Bielizna-damska/julimex/ 0-10|/Bielizna-damska/kabak/ 0-10|/Bielizna-damska/key/|/Bielizna-damska/kinga/|/Bielizna-damska/konrad/|/Bielizna-damska/l-l/ 0-10|
/Bielizna-damska/lama/|/Bielizna-damska/leinle/ 0-10|/Bielizna-damska/livco-corsetti/ 0-10|/Bielizna-damska/livia-corsetti/|/Bielizna-damska/luna/ 0-10|/Bielizna-damska/lupo-line/ 0-10|/Bielizna-damska/marko/ 0-10|/Bielizna-damska/mat/|/Bielizna-damska/mitex/ 0-10|
/Bielizna-damska/modo/ 0-10|/Bielizna-damska/mona/ 0-10|/Bielizna-damska/nipplex/|/Bielizna-damska/obsessive/|/Bielizna-damska/regina/|/Bielizna-damska/rossli/ 0-10|/Bielizna-damska/roza/|/Bielizna-damska/self/ 0-10|/Bielizna-damska/sensis/ 0-10|
/Bielizna-damska/sesto-senso/ 0-10|/Bielizna-damska/shepa/ 0-10|/Bielizna-damska/taro/ 0-10|/Bielizna-damska/vena/|/Bielizna-damska/veneziana/ 0-10|/Bielizna-damska/wol-bar/ 0-10|/Bielizna-damska/wolbar/|/Bielizna-meska/alpha-male/ 0-10|/Bielizna-meska/atlantic/|
/Bielizna-meska/cornette/|/Bielizna-meska/de-lafense/ 0-10|/Bielizna-meska/eso-hen/ 0-10|/Bielizna-meska/henderson/|/Bielizna-meska/key/|/Bielizna-meska/lama/|/Bielizna-meska/luna/ 0-10|/Bielizna-meska/pierre-cardin/|/Bielizna-meska/regina/ 0-10|
/Bielizna-meska/rossli/ 0-10|/Bielizna-meska/sesto-senso/|/Bielizna-meska/shepa/ 0-10|/Bielizna-meska/spox-sox/ 0-10|/Bielizna-meska/taro/ 0-10|/Bielizna-meska/umbro/ 0-10|/Bizuteria-damska/anemon-atelier/ 0-10|/Bizuteria-damska/be-the-one/ 0-10|
/Bizuteria-damska/bizuteria-z-talerzy/ 0-10|/Bizuteria-damska/boske/ 0-10|/Bizuteria-damska/by-milla/ 0-10|/Bizuteria-damska/cloe/ 0-10|/Bizuteria-damska/coconut-jewellery/ 0-10|/Bizuteria-damska/czaki-bransoletki/ 0-10|/Bizuteria-damska/elemthebrand/ 0-10|
/Bizuteria-damska/eminence/ 0-10|/Bizuteria-damska/energetix-niemcy/ 0-10|/Bizuteria-damska/exclusive-by-milla/ 0-10|/Bizuteria-damska/grol-jewellery/ 0-10|/Bizuteria-damska/hellaclay/ 0-10|/Bizuteria-damska/iloko/ 0-10|
/Bizuteria-damska/kaktusia/ 0-10|/Bizuteria-damska/lei-handmade/ 0-10|/Bizuteria-damska/lemon-lovely/ 0-10|/Bizuteria-damska/luo/ 0-10|/Bizuteria-damska/maanuela/ 0-10|/Bizuteria-damska/magneska/ 0-10|/Bizuteria-damska/mariaela/ 0-10|/Bizuteria-damska/mazuni/ 0-10|
/Bizuteria-damska/milita-nikonorov/ 0-10|/Bizuteria-damska/miss-glow/ 0-10|/Bizuteria-damska/modelinova/ 0-10|/Bizuteria-damska/mona/ 0-10|/Bizuteria-damska/muamua-design/ 0-10|/Bizuteria-damska/myness/ 0-10|/Bizuteria-damska/no-logo/ 0-10|/Bizuteria-damska/olga-zielinska/ 0-10|
/Bizuteria-damska/polly-design/ 0-10|/Bizuteria-damska/sentiell/ 0-10|/Bizuteria-damska/shambala/ 0-10|/Bizuteria-damska/sotho/ 0-10|/Bizuteria-damska/staviori/ 0-10|/Bizuteria-damska/staviori-wlochy/ 0-10|/Bizuteria-damska/vander-jewelry/ 0-10|/Bizuteria-damska/venus-galeria/ 0-10|
/Bizuteria-damska/wec-twoj-jubiler/ 0-10|/Bizuteria-damska/yenoo/ 0-10|/Bluzki-damskie/eldar/|/Koszulki-meskie/koszulk/ 0-10|/Spodnice/figl/|
/Spodnice/katrus/|/Spodnice/lanti/ 0-10|/Spodnice/moe/ 0-10|/Spodnice/moremoi/ 0-10|/Spodnice/nife/|/Spodnice/nommo/ 0-10|/Spodnice/tessita/ 0-10|/Sukienki/awama/|/Sukienki/dursi/|/Sukienki/eva-lola/ 0-10|
/Sukienki/figl/|/Sukienki/fobya/|/Sukienki/freeshion/|/Sukienki/imesia/|/Sukienki/infinite-you/|/Sukienki/ivon/|/Sukienki/katrus/|/Sukienki/lanti/|/Sukienki/lemoniade/|/Sukienki/lou-lou/|/Sukienki/makadamia/|/Sukienki/makeover/|
/Sukienki/merribel/|/Sukienki/milita-nikonorov/ 0-10|/Sukienki/moe/|/Sukienki/moremoi/ 0-10|/Sukienki/nife/|/Sukienki/nommo/|/Sukienki/numoco/|/Sukienki/pawelkuzik/ 0-10|/Sukienki/sale/|/Sukienki/soky-soka/|/Sukienki/tessita/|/Torby-meskie/always-wild/ 0-10|
/Torby-meskie/br-drene/ 0-10|/Torby-meskie/mcklein/ 0-10|/Torby-meskie/paolo-peruzzi/ 0-10|/Torby-meskie/solier/|/Torebki-damskie/felice/ 0-10|/Torebki-damskie/rovicky/ 0-10|/Zegarki-damskie/geneva/|/Zegarki-damskie/no-logo/ 0-10|/Zegarki-meskie/geneva/|
/Zegarki-meskie/skmei/|/Bielizna-nocna/anais/ 0-10|/Bielizna-nocna/aruelle/ 0-10|/Bielizna-nocna/babell/ 0-10|/Bielizna-nocna/babella/ 0-10|/Bielizna-nocna/betina/ 0-10|/Bielizna-nocna/cana/ 0-10|/Bielizna-nocna/cornette/ 0-10|
/Bielizna-nocna/de-lafense/ 0-10|/Bielizna-nocna/dkaren/ 0-10|/Bielizna-nocna/donna/|/Bielizna-nocna/eldar/ 0-10|/Bielizna-nocna/eso-hen/ 0-10|/Bielizna-nocna/gorsenia/ 0-10|/Bielizna-nocna/henderson-ladies/ 0-10|/Bielizna-nocna/irall/ 0-10|/Bielizna-nocna/italian-fashion/ 0-10|
/Bielizna-nocna/key/ 0-10|/Bielizna-nocna/l-l/ 0-10|/Bielizna-nocna/leinle/ 0-10|/Bielizna-nocna/livco-corsetti/ 0-10|/Bielizna-nocna/luna/ 0-10|/Bielizna-nocna/lupo-line/ 0-10|/Bielizna-nocna/nipplex/ 0-10|/Bielizna-nocna/nipplex-by-night/ 0-10|/Bielizna-nocna/regina/ 0-10|
/Bielizna-nocna/rossli/ 0-10|/Bielizna-nocna/sensis/ 0-10|/Bielizna-nocna/taro/ 0-10|/Biustonosze/ava/|/Biustonosze/ava-lingerie/ 0-10|/Biustonosze/axami/|/Biustonosze/gaia/|/Biustonosze/gorsenia/|/Biustonosze/gorteks/|/Biustonosze/julimex/|
/Biustonosze/kinga/|/Biustonosze/konrad/|/Biustonosze/lupo-line/ 0-10|/Biustonosze/mat/|/Biustonosze/nipplex/|/Biustonosze/vena/|/Body-damskie/eldar/ 0-10|/Body-damskie/figl/ 0-10|/Body-damskie/mitex/ 0-10|
/Bransoletki/cloe/ 0-10|/Bransoletki/energetix-niemcy/ 0-10|/Bransoletki/iloko/ 0-10|/Bransoletki/lei-handmade/ 0-10|/Bransoletki/luo/ 0-10|/Bransoletki/magneska/ 0-10|/Bransoletki/mona/ 0-10|/Bransoletki/myness/ 0-10|
/Bransoletki/sentiell/ 0-10|/Bransoletki/yenoo/ 0-10|/Broszki/elemthebrand/ 0-10|/Czapki-damskie/kamea/|/Kapielowki/alpha-male/|/Kapielowki/henderson/|/Kapielowki/shepa/|/Kolczyki/anemon-atelier/ 0-10|
/Kolczyki/bizuteria-z-talerzy/ 0-10|/Kolczyki/cloe/|/Kolczyki/hellaclay/ 0-10|/Kolczyki/iloko/ 0-10|/Kolczyki/luo/ 0-10|/Kolczyki/maanuela/ 0-10|/Kolczyki/mazuni/ 0-10|/Kolczyki/modelinova/ 0-10|/Kolczyki/mona/ 0-10|/Kolczyki/myness/ 0-10|/Kolczyki/no-logo/ 0-10|
/Kolczyki/olga-zielinska/ 0-10|/Kolczyki/sentiell/ 0-10|/Kolczyki/shambala/|/Kolczyki/sotho/|/Kolczyki/staviori-wlochy/ 0-10|/Kolczyki/wec-twoj-jubiler/ 0-10|/Kolczyki/yenoo/ 0-10|/Kopertowki/felice/ 0-10|/Kopertowki/rovicky/ 0-10|/Lancuszki/sentiell/ 0-10|
/Lancuszki/staviori-wlochy/ 0-10|/Majtki-damskie/atlantic/|/Majtki-damskie/ava/|/Majtki-damskie/babell/|/Majtki-damskie/donella/|/Majtki-damskie/eldar/|/Majtki-damskie/emili/|/Majtki-damskie/ewana/|/Majtki-damskie/gabidar/|
/Majtki-damskie/gaia/ 0-10|/Majtki-damskie/gorsenia/|/Majtki-damskie/gorteks/ 0-10|/Majtki-damskie/julimex/|/Majtki-damskie/key/|/Majtki-damskie/kinga/ 0-10|/Majtki-damskie/lama/|/Majtki-damskie/lupo-line/ 0-10|/Majtki-damskie/mat/ 0-10|/Majtki-damskie/mitex/ 0-10|
/Majtki-damskie/modo/|/Majtki-damskie/nipplex/ 0-10|/Majtki-damskie/roza/ 0-10|/Majtki-damskie/vena/|/Majtki-damskie/wol-bar/ 0-10|/Majtki-damskie/wolbar/|/Majtki-meskie/atlantic/|/Majtki-meskie/cornette/|/Majtki-meskie/henderson/|/Majtki-meskie/key/|
/Majtki-meskie/lama/|/Majtki-meskie/pierre-cardin/ 0-10|/Majtki-meskie/rossli/ 0-10|/Majtki-meskie/sesto-senso/ 0-10|/Majtki-meskie/umbro/|/Naszyjniki/anemon-atelier/ 0-10|/Naszyjniki/by-milla/ 0-10|/Naszyjniki/cloe/ 0-10|/Naszyjniki/iloko/ 0-10|
/Naszyjniki/luo/ 0-10|/Naszyjniki/milita-nikonorov/ 0-10|/Naszyjniki/mona/ 0-10|/Naszyjniki/myness/ 0-10|/Naszyjniki/sentiell/ 0-10|/Naszyjniki/sotho/|/Naszyjniki/staviori-wlochy/ 0-10|/Okulary-damskie/arctica/|/Okulary-damskie/montana/ 0-10|/Okulary-meskie/arctica/|
/Okulary-meskie/draco/ 0-10|/Okulary-meskie/lozano/ 0-10|/Okulary-meskie/montana/ 0-10|/Okulary-meskie/polarized/ 0-10|/Okulary-meskie/stylion/ 0-10|/Okulary-meskie/sunoptic/ 0-10|/Paski-damskie/e-zegarki/ 0-10|/Paski-damskie/rovicky/ 0-10|/Paski-meskie/br-drene/ 0-10|
/Paski-meskie/e-zegarki/ 0-10|/Paski-meskie/solier/ 0-10|/Pasy-do-ponczoch/julimex/ 0-10|/Pierscionki/eminence/ 0-10|/Pierscionki/mona/ 0-10|/Pierscionki/sentiell/ 0-10|/Pierscionki/staviori-wlochy/ 0-10|/Pierscionki/wec-twoj-jubiler/ 0-10|
/Pizamy-meskie/cornette/|/Pizamy-meskie/henderson/|/Pizamy-meskie/key/|/Pizamy-meskie/luna/|/Pizamy-meskie/regina/|/Pizamy-meskie/rossli/|/Pizamy-meskie/taro/|/Ponczochy-damskie/fiore/ 0-10|/Ponczochy-damskie/gabriella/ 0-10|
/Ponczochy-damskie/gatta/ 0-10|/Ponczochy-damskie/veneziana/ 0-10|/Portfele-damskie/4u-cavaldi/ 0|/Portfele-damskie/lorenti/|/Portfele-damskie/milano-design/ 0-10|/Portfele-damskie/producent-niezdefiniowany/ 0-10|/Portfele-damskie/rovicky/|/Portfele-damskie/valentini/|
/Portfele-meskie/always-wild/|/Portfele-meskie/br-drene/ 0-10|/Portfele-meskie/buffalo-wild/ 0-10|/Portfele-meskie/pierre-andreus/ 0-10|/Portfele-meskie/rovicky/|/Portfele-meskie/samsonite/|/Portfele-meskie/solier/ 0-10|/Portfele-meskie/valentini/|
/Rajstopy-damskie/fiore/ 0-10|/Rajstopy-damskie/gabriella/|/Rajstopy-damskie/gatta/|/Rajstopy-damskie/knittex/ 0-10|/Rajstopy-damskie/livco-corsetti/ 0-10|/Rajstopy-damskie/mona/ 0-10|/Rajstopy-damskie/sesto-senso/ 0-10|/Rajstopy-damskie/veneziana/|
/Skarpetki-damskie/kabak/ 0-10|/Skarpetki-meskie/spox-sox/ 0-10|/Spodnice-mini/ivon/ 0-10|/Spodnice-olowkowe/figl/ 0-10|/Spodnice-olowkowe/moe/ 0-10|/Spodnice-olowkowe/moremoi/ 0-10|/Spodnice-olowkowe/nife/ 0-10|/Spodnice-rozkloszowane/nife/ 0-10|
/Stroje-kapielowe-damskie/marko/|/Stroje-kapielowe-damskie/self/|/Stroje-kapielowe-damskie/shepa/|/Sukienki-asymetryczne/katrus/ 0-10|
/Sukienki-asymetryczne/makadamia/ 0-10|/Sukienki-asymetryczne/moe/ 0-10|/Sukienki-asymetryczne/nommo/ 0-10|/Sukienki-asymetryczne/numoco/ 0-10|/Sukienki-do-pracy/moremoi/ 0-10|/Sukienki-dresowe/makadamia/ 0-10|
/Sukienki-dresowe/moe/ 0-10|/Sukienki-dresowe/tessita/ 0-10|/Sukienki-dzinsowe/numoco/ 0-10|/Sukienki-koktajlowe/nommo/ 0-10|/Sukienki-koronkowe/nommo/ 0-10|/Sukienki-koronkowe/numoco/ 0-10|
/Sukienki-maxi/makadamia/ 0-10|/Sukienki-maxi/numoco/ 0-10|/Sukienki-midi/awama/ 0-10|/Sukienki-midi/figl/ 0-10|/Sukienki-midi/freeshion/ 0-10|/Sukienki-midi/katrus/ 0-10|/Sukienki-midi/makadamia/ 0-10|/Sukienki-midi/moe/ 0-10|/Sukienki-midi/moremoi/ 0-10|
/Sukienki-midi/nife/ 0-10|/Sukienki-midi/nommo/ 0-10|/Sukienki-midi/numoco/ 0-10|/Sukienki-mini/awama/ 0-10|/Sukienki-mini/dursi/ 0-10|/Sukienki-mini/ivon/ 0-10|/Sukienki-mini/moe/ 0-10|/Sukienki-mini/nommo/ 0-10|/Sukienki-mini/numoco/ 0-10|/Sukienki-na-wesele/numoco/|
/Sukienki-olowkowe/dursi/ 0-10|/Sukienki-olowkowe/ivon/ 0-10|/Sukienki-olowkowe/merribel/ 0-10|/Sukienki-olowkowe/moe/ 0-10|/Sukienki-olowkowe/nife/ 0-10|/Sukienki-olowkowe/nommo/ 0-10|/Sukienki-olowkowe/numoco/ 0-10|/Sukienki-plus-size/nommo/ 0-10|/Sukienki-rozkloszowane/awama/ 0-10|
/Sukienki-rozkloszowane/figl/ 0-10|/Sukienki-rozkloszowane/katrus/ 0-10|/Sukienki-rozkloszowane/lemoniade/ 0-10|/Sukienki-rozkloszowane/makadamia/ 0-10|/Sukienki-rozkloszowane/merribel/ 0-10|/Sukienki-rozkloszowane/moe/ 0-10|
/Sukienki-rozkloszowane/moremoi/ 0-10|/Sukienki-rozkloszowane/nife/ 0-10|/Sukienki-rozkloszowane/nommo/ 0-10|/Sukienki-rozkloszowane/numoco/ 0-10|/Sukienki-rozkloszowane/tessita/ 0-10|/Sukienki-sportowe/moe/ 0-10|/Sukienki-sportowe/numoco/ 0-10|/Sukienki-trapezowe/awama/ 0-10|
/Sukienki-trapezowe/ivon/ 0-10|/Sukienki-trapezowe/lemoniade/ 0-10|/Sukienki-trapezowe/makadamia/ 0-10|/Sukienki-trapezowe/moe/ 0-10|/Sukienki-trapezowe/nommo/ 0-10|/Sukienki-trapezowe/numoco/ 0-10|/Sukienki-wieczorowe/dursi/ 0-10|
/Sukienki-wieczorowe/eva-lola/ 0-10|/Sukienki-wieczorowe/ivon/ 0-10|/Sukienki-wieczorowe/numoco/ 0-10|/Sukienki-wizytowe/awama/ 0-10|/Sukienki-wizytowe/dursi/ 0-10|/Sukienki-wizytowe/figl/ 0-10|/Sukienki-wizytowe/fobya/ 0-10|/Sukienki-wizytowe/imesia/ 0-10|
/Sukienki-wizytowe/infinite-you/ 0-10|/Sukienki-wizytowe/ivon/ 0-10|/Sukienki-wizytowe/katrus/ 0-10|/Sukienki-wizytowe/lanti/ 0-10|/Sukienki-wizytowe/lemoniade/ 0-10|/Sukienki-wizytowe/makadamia/ 0-10|/Sukienki-wizytowe/makeover/ 0-10|/Sukienki-wizytowe/merribel/ 0-10|
/Sukienki-wizytowe/moe/ 0-10|/Sukienki-wizytowe/nife/ 0-10|/Sukienki-wizytowe/nommo/ 0-10|/Sukienki-wizytowe/numoco/ 0-10|/Sukienki-wizytowe/tessita/ 0-10|/Sukienki-z-cekinami/awama/ 0-10|/Szlafroki-meskie/de-lafense/ 0-10|/T-shirty-meskie/koszulk/ 0-10|
/Teczki-meskie/paolo-peruzzi/ 0-10|/Torby-meskie-na-ramie/solier/|/Torby-skorzane-meskie/always-wild/ 0-10|/Torby-skorzane-meskie/br-drene/ 0-10|/Torby-skorzane-meskie/paolo-peruzzi/ 0-10|/Torby-skorzane-meskie/solier/|/Wisiorki/mona/ 0-10|/Wisiorki/polly-design/ 0-10|
/Wisiorki/staviori-wlochy/ 0-10|/Wisiorki/wec-twoj-jubiler/ 0-10|/Zawieszki/energetix-niemcy/ 0-10|/Zawieszki/sentiell/ 0-10|/Biustonosze-koronkowe/ava/ 0-10|/Biustonosze-koronkowe/gaia/ 0-10|
/Biustonosze-koronkowe/gorsenia/ 0-10|/Biustonosze-koronkowe/gorteks/ 0-10|/Biustonosze-koronkowe/kinga/ 0-10|/Biustonosze-koronkowe/lupo-line/ 0-10|/Biustonosze-koronkowe/mat/ 0-10|/Biustonosze-koronkowe/nipplex/ 0-10|
/Biustonosze-miekkie/gaia/ 0-10|/Biustonosze-miekkie/gorsenia/|/Biustonosze-push-up/kinga/ 0-10|/Biustonosze-usztywniane/ava/ 0-10|/Biustonosze-usztywniane/gaia/ 0-10|
/Biustonosze-usztywniane/kinga/ 0-10|/Bokserki-meskie/atlantic/|/Bokserki-meskie/cornette/|/Bokserki-meskie/henderson/|/Bokserki-meskie/key/|/Bokserki-meskie/lama/|/Bokserki-meskie/pierre-cardin/|/Bokserki-meskie/rossli/ 0-10|
/Bokserki-meskie/sesto-senso/|/Bokserki-meskie/umbro/|/Bransoletki-swarovski/myness/ 0-10|/Bransoletki-sznurkowe/sentiell/ 0-10|/Figi-damskie/atlantic/|/Figi-damskie/ava/|/Figi-damskie/babell/|/Figi-damskie/donella/ 0-10|
/Figi-damskie/eldar/|/Figi-damskie/emili/ 0-10|/Figi-damskie/ewana/|/Figi-damskie/gabidar/|/Figi-damskie/gaia/|/Figi-damskie/gorsenia/|/Figi-damskie/julimex/|/Figi-damskie/key/|/Figi-damskie/kinga/|/Figi-damskie/lama/|/Figi-damskie/lupo-line/ 0-10|
/Figi-damskie/mat/ 0-10|/Figi-damskie/mitex/ 0-10|/Figi-damskie/modo/|/Figi-damskie/nipplex/|/Figi-damskie/wol-bar/|/Figi-damskie/wolbar/|/Koszulki-nocne/anais/ 0-10|/Koszulki-nocne/aruelle/ 0-10|/Koszulki-nocne/babell/ 0-10|/Koszulki-nocne/babella/ 0-10|
/Koszulki-nocne/betina/ 0-10|/Koszulki-nocne/cana/ 0-10|/Koszulki-nocne/cornette/ 0-10|/Koszulki-nocne/de-lafense/ 0-10|/Koszulki-nocne/dkaren/ 0-10|/Koszulki-nocne/donna/|/Koszulki-nocne/eldar/ 0-10|/Koszulki-nocne/gorsenia 0-10/|
/Koszulki-nocne/henderson-ladies/ 0-10|/Koszulki-nocne/irall/ 0-10|/Koszulki-nocne/italian-fashion/ 0-10|/Koszulki-nocne/key/ 0-10|/Koszulki-nocne/leinle/ 0-10|/Koszulki-nocne/livco-corsetti/ 0-10|/Koszulki-nocne/luna/ 0-10|/Koszulki-nocne/lupo-line/ 0-10|/Koszulki-nocne/nipplex/ 0-10|
/Koszulki-nocne/regina/ 0-10|/Koszulki-nocne/sensis/ 0-10|/Koszulki-nocne/taro/ 0-10|/Pizamy-damskie/aruelle/ 0-10|/Pizamy-damskie/babella/|/Pizamy-damskie/cana/|/Pizamy-damskie/cornette/|/Pizamy-damskie/de-lafense/ 0-10|/Pizamy-damskie/donna/|
/Pizamy-damskie/henderson-ladies/ 0-10|/Pizamy-damskie/irall/ 0-10|/Pizamy-damskie/italian-fashion/|/Pizamy-damskie/key/|/Pizamy-damskie/leinle/ 0-10|/Pizamy-damskie/luna/|/Pizamy-damskie/regina/|/Pizamy-damskie/rossli/ 0-10|/Pizamy-damskie/sensis/|
/Pizamy-damskie/taro/|/Slipy-meskie/atlantic/|/Slipy-meskie/cornette/|/Slipy-meskie/henderson/|/Slipy-meskie/key/|/Slipy-meskie/sesto-senso/|/Stringi-damskie/ava/|/Stringi-damskie/gabidar/|/Stringi-damskie/kinga/|/Stringi-damskie/nipplex/ 0|
/Stringi-damskie/wol-bar/ 0|/Stroje-kapielowe-dwuczesciowe/marko/|/Stroje-kapielowe-dwuczesciowe/self/|/Stroje-kapielowe-jednoczesciowe/marko/|/Stroje-kapielowe-jednoczesciowe/shepa/ 0-10|/Szlafroki-damskie/aruelle/ 0-10|/Szlafroki-damskie/de-lafense/ 0-10|
/Szlafroki-damskie/dkaren/ 0-10|/Szlafroki-damskie/irall/ 0-10|/Szlafroki-damskie/l-l/ 0-10|/Akcesoria-meskie/wyprzedaze/ 0-10|/Bielizna-damska/wyprzedaze/|/Bielizna-meska/wyprzedaze/ 0-10|/Spodnice/wyprzedaze/ 0-10|/Sukienki/wyprzedaze/|
/Bielizna-nocna/wyprzedaze/ 0-10|/Biustonosze/wyprzedaze/|/Majtki-damskie/wyprzedaze/ 0-10|/Majtki-meskie/wyprzedaze/ 0-10|/Okulary-meskie/wyprzedaze/ 0-10|/Skarpetki-damskie/wyprzedaze/ 0-10|/Sukienki-midi/wyprzedaze/ 0-10|/Sukienki-olowkowe/wyprzedaze/ 0-10|
/Sukienki-rozkloszowane/wyprzedaze/ 0-10|/Sukienki-wizytowe/wyprzedaze/ 0-10|/Figi-damskie/wyprzedaze/ 0-10|/Akcesoria-damskie/welniane/ 0-10|/Akcesoria-damskie/z-poliamidu/ 0-10|/Akcesoria-damskie/skorzane/ 0-10|/Akcesoria-damskie/lniane/ 0-10|/Bielizna-damska/dzianinowe/ 0-10|
/Bielizna-damska/z-poliestru/ 0-10|/Bielizna-damska/welniane/|/Bielizna-damska/bawelniane/|/Bielizna-damska/z-elastanu/ 0-10|/Bielizna-damska/z-wiskozy/ 0-10|/Bielizna-damska/lniane/|/Bluzki-damskie/z-poliestru/ 0-10|/Bluzki-damskie/welniane/|
/Bluzki-damskie/bawelniane/|/Bluzki-damskie/z-elastanu/ 0-10|/Bluzki-damskie/z-wiskozy/|/Bluzki-damskie/lniane/|/Spodnice/dzianinowe/|/Spodnice/z-poliestru/ 0-10|/Spodnice/welniane/|/Spodnice/bawelniane/|/Spodnice/z-elastanu/ 0-10|/Spodnice/z-wiskozy/|
/Spodnice/lniane/|/Sukienki/dzianinowe/|/Sukienki/z-poliestru/|/Sukienki/welniane/|/Sukienki/bawelniane/|/Sukienki/z-poliamidu/ 0-10|/Sukienki/z-elastanu/ 0-10|/Sukienki/z-wiskozy/|/Sukienki/z-nylonu/|/Sukienki/z-tkaniny/|/Sukienki/z-szyfonu/|
/Sukienki/lniane/|/Torby-meskie/ze-skory-ekologicznej/ 0-10|/Torebki-damskie/skorzane/|/Torebki-damskie/ze-skory-ekologicznej/|/Bielizna-nocna/dzianinowe/ 0-10|/Bielizna-nocna/z-poliestru/ 0-10|/Bielizna-nocna/welniane/ 0-10|/Bielizna-nocna/bawelniane/|
/Bielizna-nocna/z-elastanu/ 0-10|/Bielizna-nocna/z-wiskozy/ 0-10|/Bielizna-nocna/lniane/ 0-10|/Bluzki-oversize/z-elastanu/ 0-10|/Bluzki-oversize/z-wiskozy/ 0-10|/Czapki-damskie/welniane/|/Czapki-damskie/z-poliamidu/ 0-10|/Czapki-damskie/lniane/ 0-10|/Kopertowki/skorzane/|
/Kopertowki/ze-skory-ekologicznej/ 0-10|/Paski-damskie/skorzane/|/Plecaki-damskie/skorzane/|/Spodnice-midi/z-poliestru/ 0-10|/Spodnice-midi/z-elastanu/ 0-10|/Spodnice-midi/z-wiskozy/ 0-10|/Spodnice-mini/z-poliestru/ 0-10|/Spodnice-mini/welniane/ 0-10|
/Spodnice-mini/z-elastanu/ 0-10|/Spodnice-mini/lniane/ 0-10|/Spodnice-olowkowe/dzianinowe/|/Spodnice-olowkowe/z-poliestru/ 0-10|/Spodnice-olowkowe/welniane/|/Spodnice-olowkowe/bawelniane/ 0-10|/Spodnice-olowkowe/z-elastanu/ 0-10|/Spodnice-olowkowe/z-wiskozy/ 0-10|
/Spodnice-olowkowe/lniane/ 0-10|/Spodnice-rozkloszowane/z-poliestru/ 0-10|/Spodnice-rozkloszowane/z-elastanu/ 0-10|/Spodnice-rozkloszowane/z-wiskozy/ 0-10|/Spodnice-trapezowe/z-poliestru/ 0-10|/Spodnice-trapezowe/z-wiskozy/ 0-10|/Sukienki-asymetryczne/dzianinowe/ 0-10|
/Sukienki-asymetryczne/z-poliestru/ 0-10|/Sukienki-asymetryczne/welniane/ 0-10|/Sukienki-asymetryczne/bawelniane/ 0-10|/Sukienki-asymetryczne/z-elastanu/ 0-10|/Sukienki-asymetryczne/z-wiskozy/ 0-10|/Sukienki-asymetryczne/lniane/ 0-10|/Sukienki-do-pracy/dzianinowe/ 0-10|
/Sukienki-do-pracy/z-poliestru/ 0-10|/Sukienki-do-pracy/welniane/ 0-10|/Sukienki-do-pracy/bawelniane/ 0-10|/Sukienki-do-pracy/z-elastanu/ 0-10|/Sukienki-do-pracy/z-wiskozy/ 0-10|/Sukienki-do-pracy/lniane/ 0-10|/Sukienki-dresowe/dzianinowe/|/Sukienki-dresowe/z-poliestru/ 0-10|
/Sukienki-dresowe/welniane/ 0-10|/Sukienki-dresowe/bawelniane/|/Sukienki-dresowe/z-elastanu/ 0-10|/Sukienki-dresowe/z-wiskozy/ 0-10|/Sukienki-dresowe/lniane/ 0-10|/Sukienki-dzinsowe/z-poliestru/ 0-10|/Sukienki-dzinsowe/z-elastanu/ 0-10|/Sukienki-dzinsowe/z-wiskozy/ 0-10|
/Sukienki-gorsetowe/z-poliestru/ 0-10|/Sukienki-koktajlowe/z-poliestru/ 0-10|/Sukienki-koktajlowe/z-elastanu/ 0-10|/Sukienki-koktajlowe/z-wiskozy/ 0-10|/Sukienki-koktajlowe/lniane/ 0-10|/Sukienki-koronkowe/z-poliestru/ 0-10|/Sukienki-koronkowe/z-elastanu/ 0-10|
/Sukienki-koronkowe/z-wiskozy/ 0-10|/Sukienki-koszulowe/z-poliestru/ 0-10|/Sukienki-koszulowe/z-elastanu/ 0-10|/Sukienki-koszulowe/z-wiskozy/ 0-10|/Sukienki-maxi/dzianinowe/|/Sukienki-maxi/z-poliestru/ 0-10|/Sukienki-maxi/welniane/ 0-10|/Sukienki-maxi/bawelniane/|
/Sukienki-maxi/z-elastanu/ 0-10|/Sukienki-maxi/z-wiskozy/|/Sukienki-maxi/lniane/|/Sukienki-midi/dzianinowe/|/Sukienki-midi/z-poliestru/ 0-10|/Sukienki-midi/welniane/ 0-10|/Sukienki-midi/bawelniane/|/Sukienki-midi/z-elastanu/ 0-10|/Sukienki-midi/z-wiskozy/|
/Sukienki-midi/lniane/|/Sukienki-mini/z-poliestru/ 0-10|/Sukienki-mini/welniane/ 0-10|/Sukienki-mini/bawelniane/|/Sukienki-mini/z-elastanu/ 0-10|/Sukienki-mini/z-wiskozy/ 0-10|/Sukienki-mini/lniane/ 0-10|/Sukienki-na-wesele/z-poliestru/|/Sukienki-na-wesele/z-elastanu/ 0-10|
/Sukienki-na-wesele/z-wiskozy/|/Sukienki-olowkowe/z-poliestru/ 0-10|/Sukienki-olowkowe/welniane/ 0-10|/Sukienki-olowkowe/bawelniane/|/Sukienki-olowkowe/z-elastanu/ 0-10|/Sukienki-olowkowe/z-wiskozy/ 0-10|/Sukienki-olowkowe/lniane/ 0-10|/Sukienki-pastelowe/z-poliestru/ 0-10|
/Sukienki-plus-size/z-poliestru/ 0-10|/Sukienki-plus-size/z-wiskozy/ 0-10|/Sukienki-rozkloszowane/dzianinowe/|/Sukienki-rozkloszowane/z-poliestru/ 0-10|/Sukienki-rozkloszowane/welniane/ 0-10|/Sukienki-rozkloszowane/bawelniane/0-10|/Sukienki-rozkloszowane/z-elastanu/ 0-10|
/Sukienki-rozkloszowane/z-wiskozy/ 0-10|/Sukienki-rozkloszowane/lniane/ 0-10|/Sukienki-sportowe/z-poliestru/ 0-10|/Sukienki-sportowe/welniane/ 0-10|/Sukienki-sportowe/bawelniane/|/Sukienki-sportowe/z-elastanu/ 0-10|/Sukienki-sportowe/z-wiskozy/ 0-10|/Sukienki-sportowe/lniane/ 0-10|
/Sukienki-trapezowe/dzianinowe/|/Sukienki-trapezowe/z-poliestru/ 0-10|/Sukienki-trapezowe/welniane/ 0-10|/Sukienki-trapezowe/bawelniane/ 0-10|/Sukienki-trapezowe/z-elastanu/ 0-10|/Sukienki-trapezowe/z-wiskozy/ 0-10|/Sukienki-trapezowe/lniane/ 0-10|/Sukienki-wieczorowe/z-poliestru/ 0-10|
/Sukienki-wieczorowe/z-elastanu/ 0-10|/Sukienki-wieczorowe/z-wiskozy/ 0-10|/Sukienki-wizytowe/dzianinowe/ 0-10|/Sukienki-wizytowe/z-poliestru/ 0-10|/Sukienki-wizytowe/welniane/ 0-10|/Sukienki-wizytowe/bawelniane 0-10/|/Sukienki-wizytowe/z-poliamidu/ 0-10|/Sukienki-wizytowe/z-elastanu/ 0-10|
/Sukienki-wizytowe/z-wiskozy/ 0-10|/Sukienki-wizytowe/z-nylonu/ 0-10|/Sukienki-wizytowe/z-szyfonu/ 0-10|/Sukienki-wizytowe/lniane/ 0-10|/Sukienki-z-cekinami/z-poliestru/ 0-10|/Sukienki-z-cekinami/z-elastanu/ 0-10|/Sukienki-za-kolano/z-poliestru/ 0-10|/Pizamy-damskie/dzianinowe/ 0-10|
/Pizamy-damskie/z-poliestru/ 0-10|/Pizamy-damskie/welniane/ 0-10|/Pizamy-damskie/bawelniane/|/Pizamy-damskie/z-elastanu/ 0-10|/Pizamy-damskie/z-wiskozy/|/Pizamy-damskie/lniane/ 0-10|/Sukienki/na-wesele/|/Sukienki/wieczorowe/|/Sukienki/na-studniowke/|
/Sukienki-asymetryczne/wieczorowe/|/Sukienki-do-pracy/na-wesele/ 0-10|/Sukienki-koktajlowe/na-wesele/|/Sukienki-koktajlowe/wieczorowe/|/Sukienki-koronkowe/na-wesele/|/Sukienki-koronkowe/wieczorowe/|/Sukienki-koronkowe/na-studniowke/|
/Sukienki-maxi/wieczorowe/|/Sukienki-mini/na-wesele/|/Sukienki-mini/wieczorowe/|/Sukienki-na-wesele/na-wesele/|/Sukienki-olowkowe/na-wesele/|/Sukienki-olowkowe/wieczorowe/|/Sukienki-pastelowe/na-wesele/|/Sukienki-rozkloszowane/na-wesele/|
/Sukienki-rozkloszowane/wieczorowe/|/Sukienki-trapezowe/na-wesele/|/Sukienki-wieczorowe/na-wesele/|/Sukienki-wieczorowe/wieczorowe/|/Sukienki-wieczorowe/na-studniowke/|/Sukienki-wizytowe/na-wesele/|/Sukienki-wizytowe/wieczorowe/|
/Sukienki-wizytowe/na-studniowke/ 0-10|/Sukienki-z-cekinami/na-wesele/|/Sukienki-z-cekinami/wieczorowe/|/Sukienki/na-lato/|/Sukienki-do-pracy/na-lato/|/Sukienki-midi/na-lato/|/Sukienki-rozkloszowane/na-lato/|/Sukienki-wizytowe/na-lato/|
/Spodnice/casualowe/ 0-10|/Spodnice/eleganckie/|/Spodnice/klasyczne/|/Sukienki/casualowe/|/Sukienki/eleganckie/|/Sukienki/boho/|/Sukienki/klasyczne/|/Sukienki/mlodziezowe/|/Spodnice-olowkowe/eleganckie/|/Spodnice-olowkowe/klasyczne/ 0-10|
/Sukienki-asymetryczne/eleganckie/|/Sukienki-do-pracy/eleganckie/|/Sukienki-do-pracy/klasyczne/|/Sukienki-do-pracy/mlodziezowe/ 0-10|/Sukienki-koronkowe/mlodziezowe/|/Sukienki-midi/eleganckie/|/Sukienki-midi/klasyczne/|/Sukienki-mini/mlodziezowe/|
/Sukienki-na-wesele/eleganckie/|/Sukienki-olowkowe/eleganckie/|/Sukienki-olowkowe/klasyczne/|/Sukienki-olowkowe/mlodziezowe/ 0-10|/Sukienki-rozkloszowane/eleganckie/|/Sukienki-rozkloszowane/klasyczne/ 0-10|/Sukienki-rozkloszowane/mlodziezowe/|
/Sukienki-trapezowe/mlodziezowe/ 0-10|/Sukienki-wieczorowe/eleganckie/|/Sukienki-wieczorowe/mlodziezowe/|/Sukienki-wizytowe/casualowe/ 0-10|/Sukienki-wizytowe/eleganckie/|/Sukienki-wizytowe/boho/ 0-10|/Sukienki-wizytowe/klasyczne/|
/Sukienki-wizytowe/mlodziezowe/|/Bielizna-damska/z-nadrukiem/ 0-10|/Bielizna-damska/w-kwiaty/|/Bluzki-damskie/w-kwiaty/|/Spodnice/w-kwiaty/|/Sukienki/z-nadrukiem/|/Sukienki/z-aplikacja/|/Sukienki/w-kwiaty/|/Spodnice-rozkloszowane/w-kwiaty/|
/Stroje-kapielowe-damskie/z-nadrukiem/|/Stroje-kapielowe-damskie/w-kwiaty/|/Sukienki-asymetryczne/w-kwiaty/|/Sukienki-do-pracy/z-nadrukiem/ 0-10|/Sukienki-do-pracy/w-kwiaty/ 0-10|/Sukienki-maxi/w-kwiaty/|/Sukienki-midi/w-kwiaty/|/Sukienki-mini/w-kwiaty/|
/Sukienki-olowkowe/w-kwiaty/|/Sukienki-rozkloszowane/w-kwiaty/|/Sukienki-wizytowe/w-kwiaty/|/Tankini/z-nadrukiem/ 0|/Stroje-kapielowe-damskie/aquarilla/|/Sukienki-koronkowe/zlote/ 0-10|/Sukienki-koronkowe/biale/|/Sukienki/teresa-kopias/|
/Sukienki-na-wesele/czerwone/|/Sukienki-na-wesele/krotkie/|/Trampki-damskie/biale/|/Sukienki-na-wesele/dlugie/|/Sukienki-na-wesele/srebrne/|/Sukienki-midi/na-wesele/|/Sukienki-wieczorowe/srebrne/|/Buty-damskie/helios/|/Buty-damskie/jezzi/|
/Naszyjniki/kuznia-nehesi/ 0-10|/Sukienki-koronkowe/czerwone/|/Stroje-kapielowe-dwuczesciowe/krisline/ 0-10|/Sukienki-na-wesele/zielone/|/Trampki-damskie/big-star/|/Botki-damskie/juma/|/Buty-damskie/excel/ 0-10|/Buty-meskie/morek/ 0-10|/Sukienki-wieczorowe/biale/|
/Sukienki-na-wesele/niebieskie/|/Sukienki-na-wesele/w-kwiaty/|/Sukienki-plus-size/z-haftem/ 0-10|/Sukienki-trapezowe/zielone/|/Sukienki-wieczorowe/zlote/|/Buty-damskie/szare/|/Sukienki-na-wesele/blekitne/|/Sukienki-na-wesele/fioletowe/|
/Sukienki-na-wesele/wieczorowe/|/Sukienki-na-wesele/wyprzedaze/|/Botki-damskie/bezowe/|/Buty-damskie/rieker/|/Sukienki-na-wesele/rozowe/|/Sukienki-na-wesele/turkusowe/|/Sukienki-trapezowe/wyprzedaze/ 0-10|/Sukienki-wieczorowe/styl-i-ja/ 0-10|
/Trampki-damskie/czerwone/|/Buty-damskie/czerwone/|/Buty-dzieciece/big-star/|/Czolenka-damskie/tymoteo/ 0-10|/Klapki-damskie/zlote/|/Koszule-meskie/profuomo/ 0-10|/Plecaki-damskie/bamba-concept/ 0-10|/Plecaki-damskie/eleganckie/|/Sukienki-dzinsowe/lanti/ 0-10|
/Sukienki-plus-size/w-kwiaty/|/Sukienki-trapezowe/w-kwiaty/|/Biustonosze/wiesmann/|/Bluzki-damskie/bezowe/|/Buty-damskie/biale/|/Buty-damskie/na-rzepy/|/Buty-damskie/zlote/|/Gorsety-damskie/chilirose/ 0-10|/Kolczyki/joanna-muzyka-studio/ 0-10|
/Sukienki-asymetryczne/na-wesele/|/Sukienki-dresowe/dlugie/|/Sukienki-dzinsowe/dlugie/|/Sukienki-koronkowe/lejdi/ 0-10|/Sukienki-koronkowe/z-dlugim-rekawem/|/Sukienki-na-wesele/klasyczne/|/Sukienki-na-wesele/szare/|/Sukienki-na-wesele/z-jedwabiu/|
/Sukienki-na-wesele/zlote/|/Sukienki-plus-size/biale/|/Sukienki-wieczorowe/krotkie/|/Szlafroki-damskie/akcent/ 0-10|/Bizuteria-damska/flurry/ 0-10|/Body-damskie/czerwone/|/Botki-damskie/niebieskie/|/Buty-damskie/bezowe/|/Buty-damskie/big-star/|
/Buty-damskie/evento/ 0-10|/Buty-damskie/juma/|/Buty-meskie/na-lato/|/Buty-sportowe-damskie/biale/|/Czolenka-damskie/bravo-moda/ 0-10|/Klapki-damskie/kampa/ 0-10|/Kolczyki/boske/ 0-10|/Rybaczki-damskie/4f/|/Stroje-kapielowe-dwuczesciowe/w-paski/|
/Sukienki-koktajlowe/czerwone/|/Sukienki-na-wesele/bezowe/|/Sukienki-na-wesele/z-haftem/|/Sukienki-plus-size/wieczorowe/|/Sukienki-sportowe/eleganckie/|/Sukienki-wieczorowe/szare/|/Sukienki/zlote/|/Baleriny-damskie/lu-boo/|
/Bielizna-damska/heartbreaks-and-promises-lingerie/ 0-10|/Bizuteria-damska/lahovska/ 0-10|/Buty-damskie/brazowe/|/Buty-damskie/import/ 0-10|/Buty-damskie/zaxy/|/Buty-dzieciece/biale/|/Buty-dzieciece/mido-noster/|/Buty-meskie/the-north-face/|
/Czolenka-damskie/acord/|/Dresy-damskie/bawelniane/|/Koszule-meskie-sportowe/profuomo/ 0-10|/Krawaty/hemley/ 0-10|/Okulary-meskie/polarzone/ 0-10|/Spodnie-damskie/z-jerseyu/|/Stroje-kapielowe-damskie/primo/|/Stroje-kapielowe-jednoczesciowe/sapphire/ 0-10|
/Sukienki-dziewczece/biale/|/Sukienki-koktajlowe/biale/|/Sukienki-koronkowe/granatowe/|/Sukienki-maxi/na-lato/|/Sukienki-na-wesele/na-lato/|/Sukienki-plus-size/na-wesele/|/Sukienki-plus-size/szare/ 0-10|/Sukienki-z-cekinami/bezowe/ 0-10|
/Sukienki/myoko-natural-direction/ 0-10|/Trampki-damskie/czarne/|/Zegarki-damskie/biale/|';*/

// c
$noindexValues = '/Sukienki/blekitne/|/Sukienki-z-cekinami/na-wesele/|/Sukienki-na-wesele/w-kwiaty/|/Sukienki-koronkowe/na-wesele/|/Sukienki-na-wesele/krotkie/|
/Sukienki-na-wesele/dlugie/|/Sukienki/lniane/|/Sukienki-koronkowe/biale/|/Sukienki-midi/na-wesele/|/Sukienki/zlote/|/Sukienki-na-wesele/rozowe/|
/Sukienki-na-wesele/czerwone/|/Sukienki-wieczorowe/biale/|/Sukienki/w-kwiaty/|/Sukienki-rozkloszowane/na-wesele/|/Sukienki-na-wesele/eleganckie/|
/Sukienki-plus-size/wieczorowe/|/Sukienki/mlodziezowe/|/Sukienki/z-szyfonu/|/Sukienki-wieczorowe/krotkie/|/Sukienki-midi/na-lato/|
/Sukienki/bawelniane/|/Sukienki-koronkowe/czerwone/|/Sukienki-wieczorowe/czerwone/|/Sukienki/na-studniowke/|/Sukienki/zielone/|
/Sukienki/bezowe/|/Sukienki/zolte/|/Sukienki/czerwone/|/Sukienki/niebieskie/|/Sukienki-rozkloszowane/niebieskie/|
/Sukienki-na-wesele/fioletowe/|/Sukienki-koronkowe/zlote/|/Sukienki-wieczorowe/srebrne/|/Sukienki-na-wesele/zlote/|/Sukienki-maxi/lniane/|
/Sukienki-na-wesele/zielone/|/Sukienki-dresowe/dlugie/|/Sukienki-olowkowe/czerwone/|/Sukienki-na-wesele/wyprzedaze/|
/Sukienki-koktajlowe/czerwone/|/Sukienki-trapezowe/w-kwiaty/|/Sukienki-maxi/na-lato/|/Sukienki-na-wesele/niebieskie/|/Sukienki-olowkowe/na-wesele/|
/Sukienki-wieczorowe/zlote/|/Sukienki-koronkowe/z-dlugim-rekawem/|/Sukienki-na-wesele/wieczorowe/|/Sukienki-olowkowe/w-kwiaty/|
/Sukienki-plus-size/w-kwiaty/|/Sukienki-trapezowe/na-wesele/|/Sukienki/dlugie/|/Sukienki-maxi/bawelniane/|/Sukienki-maxi/z-wiskozy/|
/Sukienki-wieczorowe/granatowe/|/Sukienki/krotkie/|/Sukienki-dresowe/bawelniane/|/Sukienki-maxi/w-kwiaty/|/Sukienki-wieczorowe/szare/|
/Sukienki-wizytowe/eleganckie/|/Sukienki/biale/|/Sukienki/szare/|/Sukienki/wyprzedaze/|/Sukienki/z-dlugim-rekawem/|/Sukienki/z-nylonu/|
/Sukienki-asymetryczne/na-wesele/|/Sukienki-koronkowe/czarne/|/Sukienki-koronkowe/granatowe/|/Sukienki-koronkowe/rozowe/|
/Sukienki-koronkowe/wieczorowe/|/Sukienki-maxi/czarne/|/Sukienki-midi/lniane/|/Sukienki-mini/mlodziezowe/|/Sukienki-mini/w-kwiaty/|
/Sukienki-olowkowe/eleganckie/|/Sukienki-olowkowe/zielone/|/Sukienki-plus-size/na-wesele/|/Sukienki-rozkloszowane/biale/|
/Sukienki-trapezowe/wyprzedaze/|/Sukienki-trapezowe/zielone/|/Sukienki-wieczorowe/na-studniowke/|/Sukienki-wieczorowe/rozowe/|
/Sukienki-wizytowe/biale/|/Sukienki-wizytowe/czerwone/|/Sukienki-z-cekinami/wieczorowe/|/Sukienki/czarne/|/Sukienki/dzianinowe/|
/Sukienki/klasyczne/|/Sukienki/na-lato/|/Sukienki-wieczorowe/dlugie/|/Sukienki/granatowe/|/Sukienki/bordowe/|/Sukienki/rozowe/|
/Sukienki-rozkloszowane/czarne/|/Sukienki-rozkloszowane/czerwone/|/Sukienki-koktajlowe/na-wesele/|/Sukienki-koktajlowe/wieczorowe/|
/Sukienki-maxi/wieczorowe/|/Sukienki/eleganckie/|/Sukienki/boho/|/Sukienki-rozkloszowane/eleganckie/|/Sukienki-midi/w-kwiaty/|
/Sukienki-rozkloszowane/krotkie/|/Sukienki/z-krotkim-rekawem/|/Sukienki/brazowe/|/Sukienki/mietowe/|/Sukienki-asymetryczne/czarne/|
/Sukienki-asymetryczne/czerwone/|/Sukienki-koktajlowe/czarne/|/Sukienki-koszulowe/czarne/|/Sukienki-midi/czarne/|/Sukienki-midi/czerwone/';

$noindexList = explode('|', $noindexValues);

foreach ($noindexList as $value) {
	$newValue = trim($value);
	if (strpos($newValue, '0-10') === false) {
		echo $newValue;
	}
	
	$sql = "INSERT INTO `jos_without_noindex` (`path`)"
	."VALUES ('$newValue')"
	;
	$result = mysql_query($sql);
}
